### ISSUE TITLE
Move `WebSocketConnectionError` from `types` to `exceptions`

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#1026]
For some reason `WebSocketConnectionError` is defined in `types`, but we already have `exceptions` for our errors.

**Comment by AdemOdza** [comment]
I would like to work on this, it doesn't look like it has been started yet.

**Comment by rafalp** [comment]
Hello, you are welcome to open a PR if you want to. We are currently more busy ourselves with Ariadne GraphQL Proxy/Codegen/Modules, which is why we aren't doing much on Ariadne itself (but its pretty much feature complete)
