### ISSUE TITLE
Document an example of async usage?

### ISSUE THREAD

**Issue by ajhyndman** [mirumee/ariadne#103]
I'm not an expert in the python ecosystem, and am not sure what's required from me to support asynchronous resolvers in an Ariadne schema.  If it's possible, I'd love a brief example illustrating a working async resolver!

---

What I've tried so far (using python 3.7):

```python
from aiodataloader import DataLoader
from ariadne import ResolverMap, gql, start_simple_server

# DATA LOADERS
heroesLoader = HeroesLoader()

class HeroesLoader(DataLoader):
    async def batch_load_fn(self, keys):
        # return await batch_get_heroes()

# SCHEMA DEFINITION
type_defs = gql("""
type Query {
    heroes: [Hero!]!
}

type Hero {
    name: String!
    shortName: String
    title: String
}
""")

# RESOLVERS
query = ResolverMap("Query")
hero = ResolverMap("Hero")

@query.field("heroes")
async def resolve_heroes(*_):
    return await heroesLoader.load('_')

start_simple_server(type_defs, [query, hero])

```

**Comment by rafalp** [comment]
Hello,

`start_simple_server` is purely synchronous at this time, so you can't use `async` with it, but we have changes in the pipeline introducing proper support for async simple server we want to ship in next release:

- https://github.com/mirumee/ariadne/pull/100/
- https://github.com/patrys/starlette-ariadne

**Comment by ajhyndman** [comment]
Cool!  So I would need to implement my own WSGI layer which supports async execution, until that lands?

**Comment by rafalp** [comment]
If you want to help, please take a look on issues marked with [Help wanted](https://github.com/mirumee/ariadne/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

**Comment by ajhyndman** [comment]
I'll close this issue, since it looks like it's already on the team's radar!
