### ISSUE TITLE
Support OPTIONS requests

### ISSUE THREAD

**Issue by chriswingler** [mirumee/ariadne#104]
Hi, I keep getting a `405` when using the example code, and I'm wondering if it's a CORS issue, since my frontend and backend are running on different ports.  If so, how do I enable CORS with Ariadne?

**Comment by rafalp** [comment]
Yeop, Ariadne only supports `GET` and `POST`, missing `OPTIONS` 😂

We'll be fixing that, but in meantime you would have to wrap `GraphQLMiddleware` with a custom one that handles `OPTIONS` request and sends `CORS` headers.

**Comment by chriswingler** [comment]
Great!  Thank you @rafalp !

**Comment by mapapa** [comment]
Hi, I am currently running 0.5.0 and still get the same error. Going through the source code I cannot find an example using a CORS middleware namely one that instantites GraphQL with a cors middleware such as CORSMiddleware from starlette.middleware.cors. Any help is higly appreciated. Thanks

**Comment by patrys** [comment]
Please see https://www.starlette.io/middleware/#corsmiddleware

**Comment by mapapa** [comment]
Hihi Patrys, 

Many thanks for your reply; the buzzling bit in my case is how do I tell GaphQL to use this middleware namely:

from starlette.applications import Starlette
from starlette.middleware.cors import CORSMiddleware

app = Starlette()
app.add_middleware(CORSMiddleware, allow_origins=['*'])


then when I look into ariadne example I have
app = GraphQL(schema, debug=True, middleware=[???])

so how do I tell GraphQL to use this particular middleware?

Many thanks,
Manos

**Comment by patrys** [comment]
You can wrap one in the other:

```
CORSMiddleware(GraphQL(...))
```

**Comment by mapapa** [comment]
Excellent, many thnaks really appreciated :)

**Comment by rafalp** [comment]
Existing CORS middlewares already solve this problem, so we'll won't be doing this in Ariadne proper. Still, we'll want to eventually document this in our docs: https://github.com/mirumee/ariadne-website/issues/5

**Comment by wolfgangmeyers** [comment]
I added CORSMiddleware as a wrapper around the GraphQL(..) app, but OPTIONS is still not allowed, even after I specified it. Here is my main.py:

```
app = CORSMiddleware(
    GraphQL(schema,), allow_origins=["*"], allow_methods=("GET", "POST", "OPTIONS"),
)
```

And here is the response from an OPTIONS request:

```
$ curl -X OPTIONS -v http://localhost:8000/graphql
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> OPTIONS /graphql HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< date: Fri, 08 Nov 2019 18:48:30 GMT
< server: uvicorn
< transfer-encoding: chunked
< 
* Connection #0 to host localhost left intact
```

If someone could come up with a complete working code example of how to support OPTIONS requests from a browser-based client that would be great.

**Comment by seimsel** [comment]
I get `Redirect is not allowed for a preflight request.` when trying to subscribe to a graphql subscription.

Here is how I set up my middlewares:

```python3
app = Application(routes=routes, debug=True)
app.mount('/graphql', CORSMiddleware(GraphQL(schema, debug=True), allow_origins=['*']))
```

**Comment by patrys** [comment]
Are you sure you're not missing a trailing slash somewhere (eg. that the server is not trying to redirect you to the correct URL)?

**Comment by seimsel** [comment]
You're right. I looked at the URL forever to figure out if it was my fault, but I just didn't see it. Thanks alot. :-D

**Comment by 007vasy** [comment]
@seimsel do you have example for `graphql_sync`? how to use cors in that case?

**Comment by seimsel** [comment]
> @seimsel do you have example for `graphql_sync`? how to use cors in that case?

No. I never used this.

**Comment by newtoniumx3** [comment]
Hey guys I'm confused how do I set this up if I'm using flask_restful like so

```
from flask import Flask
from flask_restful import Api

app = Flask(__name__)
api = Api(app)
api.add_resource(Graphql, "/graphql")
```

```
from ariadne import ObjectType
from ariadne import graphql_sync
from ariadne import load_schema_from_path
from ariadne import make_executable_schema
from ariadne import snake_case_fallback_resolvers

query = ObjectType("Query")
mutation = ObjectType("Mutation")
query.set_field("one", resolve_one)
mutation.set_field("two", resolve_two)
type_defs = load_schema_from_path(SCHEMA_FILE)

schema = make_executable_schema(
    type_defs, query, mutation, snake_case_fallback_resolvers
)


class Graphql(Resource):
    def get(self):
        return PLAYGROUND_HTML, 200

    def post(self):
        data = request.get_json()

        success, result = graphql_sync(
            schema,
            data,
            context_value=request,
            debug=True
        )

        status_code = 200 if success else 400
        return result, status_code

```

**Comment by seimsel** [comment]
What do you want to setup? CORSMiddleware?

**Comment by newtoniumx3** [comment]
> What do you want to setup? CORSMiddleware?

I was just trying to get CORS setup to allow origin * as my client is on a different port. I was just playing with this I think I might have found something that works when I use flask_cors, is that the right way to do this if I use ariadne?

```
from flask_cors import CORS
from flask import Flask
app = Flask(__name__)
cors = CORS(app)
```

**Comment by seimsel** [comment]
As far as I see Ariadne never sees any http request at all (since you're using graphql_sync). So this is a question on how to handle CORS in Flask. Which it seems you are on the right track.

**Comment by newtoniumx3** [comment]
> As far as I see Ariadne never sees any http request at all (since you're using graphql_sync). So this is a question on how to handle CORS in Flask. For which it seems you are on the right track.

Thank you!
