### ISSUE TITLE
ImportError: cannot import name 'PLAYGROUND_HTML' from 'ariadne.constants' 

### ISSUE THREAD

**Issue by aesavas** [mirumee/ariadne#1046]
After updating v0.18.1, tests fail because `ImportError: cannot import name 'PLAYGROUND_HTML' from 'ariadne. constants' `. When I checked the changes, PLAYGROUND_HTML was removed from constants.py in this commit: https://github.com/mirumee/ariadne/commit/0fca6bb601fa4827741d1e3f05b0138801e134f8

So, is there any alternative way to use instead of PLAYGROUND_HTML?

**Comment by rafalp** [comment]
We've removed `PLAYGROUND_HTML` since it was no longer used in Ariadne after we [moved to GraphQL Explorers](https://ariadnegraphql.org/docs/explorers).

Where are you using `PLAYGROUND_HTML`?

**Comment by aesavas** [comment]
I checked Graphql Explorers, and it resolved my issue. I used PLAYGROUND_HTML in the view function (in Flask service). I returned PLAYGROUND_HTML in the GET request function. After the suggestion, I tried to use ExplorerApollo.html(). It handled failed tests. Thanks for help @rafalp
