### ISSUE TITLE
Federation error

### ISSUE THREAD

**Issue by SamuelAsare** [mirumee/ariadne#1065]
from ariadne import load_schema_from_path, ScalarType,SubscriptionType
from ariadne.contrib.federation import FederatedObjectType, make_federated_schema
mutation.set_field("CreateResponses", create_answers)
query.set_field("GetResponses", get_responses)

schema = make_federated_schema(type_defs, mutation, query )

app = GraphQL(schema,, debug=True)

url="http://127.0.0.1:8000"

print("🚀🚀 Server is up and running on 🔥🔥 " + url)

if __name__ == '__main__':
    app.run()
    
  The above code raises this error:
   File "C:\arms-performance-assesment-service\main.py", line 123, in <module>
    schema = make_federated_schema(type_defs, mutation, query,  subscription, snake_case_fallback_resolvers, datetime_scalar)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\arms-performance-assesment-service\venv\Lib\site-packages\ariadne\contrib\federation\schema.py", line 80, in make_federated_schema
    definitions = load_schema_from_path(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\arms-performance-assesment-service\venv\Lib\site-packages\ariadne\load_schema.py", line 30, in load_schema_from_path
    return read_graphql_file(os.path.abspath(path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\arms-performance-assesment-service\venv\Lib\site-packages\ariadne\load_schema.py", line 42, in read_graphql_file
    with open(path, "r", encoding="utf-8") as graphql_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\arms-performance-assesment-service\\venv\\Lib\\site-packages\\ariadne\\contrib\\federation\\definitions\\fed2_0.graphql'

**Comment by rafalp** [comment]
Please update to 0.19.1 which was released today.

**Comment by SamuelAsare** [comment]
Thanks, it worked
