### ISSUE TITLE
Quickstart example in readme is outdated

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#110]
We've changed API for our server utils in #100 requiring users to create executable schema on their own outside of thise. Readme example should be updated to reflect this.

**Comment by ajhyndman** [comment]
I can try updating this.  🙂

**Comment by rafalp** [comment]
Great!

AFAIR imports need to be updated to include `make_executable_schema`, and `start_simple_server` bit needs to be changed so it follows this implementation:

```
schema = make_executable_schema(type_defs, query)

start_simple_server(schema)
```
