### ISSUE TITLE
Feature request: cache query parsing and validation

### ISSUE THREAD

**Issue by lukapeschke** [mirumee/ariadne#1101]
Hello, 

First of all, thanks for your work on Ariadne, I've really enjoyed working with it until now!

I'm opening this issue because we recently ran a load test on a microservice which basically translates Graphql queries into SQL, and fetches data from postgres with sqlalchemy's async API . (we ran the tests with Python 3.11 on a single gunicorn worker with uvloop). We noticed a high CPU usage, and profiling showed that up to 30% of all the CPU time was spent in the `parse_query` and `validate_query` functions.

When I tried to implement a simpler version of the `graphql` function with a cache on query parsing and validation, the number of requests by second increased by 22%, and the median request duration decreased by 62% (P95 duration decreased by 35%).

```python
from graphql import execute as _execute_graphql
from graphql import parse as _parse_graphql

from my_service import GRAPHQL_SCHEMA

# GRAPHQL_SCHEMA is a global here to prevent lru_cache from re-hashing the same object every time, but since 
# GraphQLSchema is hashable, it could also be passed as a parameter
@lru_cache(maxsize=64)
def parse_and_validate_query(query: str) -> tuple[DocumentNode, list[GraphQLError]]:
    parsed = _parse_graphql(query)
    validation_errors = validate_query(schema=GRAPHQL_SCHEMA, document_ast=parsed)
    return parsed, validation_errors


async def execute_graphql_query(
    schema: GraphQLSchema,
    data: Any,
    *,
    debug: bool = False,
    error_formatter: ErrorFormatter = format_error,
    logger: Logger | None = None,
    context_value: Any | None = None,
) -> GraphQLResult:
    try:
        validate_data(data)
        variables, operation_name = (
            data.get("variables"),
            data.get("operationName"),
        )
        ast_document, validation_errors = parse_and_validate_query(query=data["query"])
        if validation_errors:
            return handle_graphql_errors(
                errors=validation_errors,
                logger=logger,
                error_formatter=error_formatter,
                debug=debug,
            )

        result = _execute_graphql(
            schema,
            ast_document,
            variable_values=variables,
            operation_name=operation_name,
            context_value=context_value,
        )
        if is_awaitable(result):
            result = await cast(Awaitable[ExecutionResult], result)

    except GraphQLError as error:
        return handle_graphql_errors(
            [error], logger=logger, error_formatter=error_formatter, debug=debug
        )

    return handle_query_result(result, logger=logger, error_formatter=error_formatter, debug=debug)
```

My question is: Would it make sense to have such a caching feature available in Ariadne directly ? If yes, I'd be willing to have a look

**Comment by rafalp** [comment]
Yup, in 0.20 which I would like to get out the door soonish you should be able to achieve this through setting custom parser and validator pair.

**Comment by rafalp** [comment]
@lukapeschke Hi, Ariadne 0.20 was released a while ago. Did you have a chance to experiment with it and see if it's parser and validation hooks work for you?

**Comment by lukapeschke** [comment]
@rafalp Hello, Yes, I've finally been able to try the new hooks out, and everything works as expected :slightly_smiling_face:  Would you like me to add an example to the docs ? Otherwise, I believe this can be closed

**Comment by rafalp** [comment]
Yes. I think having separate guide somewhere in the docs would be ideal. Maybe `Query caching` under `Extensions` or at the end of the `Docs` section, but thats a detail to work out later.

**Comment by rafalp** [comment]
Continuing doc discussion in linked PR
