### ISSUE TITLE
Reference resolver

### ISSUE THREAD

**Issue by Samuelasare85** [mirumee/ariadne#1108]
We are using apollo graphql for our project. We have a service called employee service with the reference resolvers written over there.
type time_tracker {
  id:                   Int     
  user_id:              Int          
  task_name:            String        
  project_name:         String        
  category:             String                  
  employee_bio:        EmployeeBio
  }

type EmployeeBio @key(fields: "user_id", resolvable: false) {
  user_id: ID!
}

 @time_tracker.field("employee_bio")
 def resolve_employee_bio(obj, user_id):
     return {"user_id": user_id}
     
 This returns only the user_id with the other fields as null
 
 Type from employee service
 type EmployeeBio @key(fields: "user_id") @shareable {
  id: ID!
  user_id: ID!
  first_name: String
  last_name: String
  other_name: String
  full_name: String
}

**Comment by rafalp** [comment]
Hello, can you please provide more context for this issue?

**Comment by SamuelAsare** [comment]
Solved, thanks
