### ISSUE TITLE
Union as directive argument

### ISSUE THREAD

**Issue by and3rson** [mirumee/ariadne#1120]
I'm trying to implement a directive that accepts a union as input:

```gql
union Value = String | Int | Boolean
directive @foo(values: [Value]) on FIELD_DEFINITION
```

However, I'm getting the following error:

```
TypeError: Argument type must be a GraphQL input type.
```

Is this a known limitation in Ariadne? I've seen a similar approach working in other GQL implementations.

**Comment by rafalp** [comment]
Hello. Ariadne is not implementing GraphQL standard itself, but instead relies on graphql-core library for that. To my knowledge unions as argument types are not allowed by GraphQL specification, hence the error as graphql-core follows the spec closely.

Can you show libraries that allow this?

**Comment by and3rson** [comment]
@rafalp thanks for a quick response!
I'm afraid you're right - we're trying to port some AWS AppSync schemas, and they sometimes use polymorphic types for directive arguments, plus there's some legacy code that's parsing those directives. So this must be specific to the internal legacy library we're using.
Are there any known workarounds to make Ariadne handle directives like this?
```
field: String
  @foo(kwargs: [{key: "a", value: 42}, {key: "b", value: "words"}, {key: "c", value: true}])
```
I'm struggling with the GQL definition for `kwargs` argument of the directive.
Sorry in advance for bringing this as a bug since this clearly looks like a question. I can move this to GitHub discussions if you like.

**Comment by and3rson** [comment]
Using a `scalar` worked - thank you!
I see your point with using static typing here, but unfortunately we cannot modify the schema - only add custom "compat" definitions.
Thank you for support!
