### ISSUE TITLE
Exceptions in resolver are caught (no traceback)

### ISSUE THREAD

**Issue by ceelian** [mirumee/ariadne#113]
Debugging resolver exception can become quite difficult, as they are caught by ariadne and I found no reasonable way to get a traceback to where the exception is happening.

```
 # Execute the query
result = graphql_sync(
      schema,
      data.get("query"),
      context_value=request,  # expose request as info.context
      variable_values=data.get("variables"),
      operation_name=data.get("operationName"),
)
log.exception('', exc_info=result.errors[0].original_error)
```
Output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/execute.py", line 664, in complete_value_catching_error
    return_type, field_nodes, info, path, result
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/execute.py", line 731, in complete_value
    raise result
graphql.error.graphql_error.GraphQLError: My exception
```

If i catch it manually in the resolver and do the log output there
```
@query.field("hello")
def resolve_hello(_, info):
    try:
        raise Exception('My exception')
        return "Hello, %s!" % 'asdf'
    except Exception as e:
        log.exception('', exc_info=e)
        raise e
```

it'll get a bit better - getting the file and line number of the error but still a quite limited traceback
```
Traceback (most recent call last):
  File "/app/webapp/core/views.py", line 35, in resolve_hello
    raise Exception('My exception')
Exception: My exception
```
I would suggest an option where you can switch on raising exceptions eg.  in development environments.  Or is there already some mechanism how to do error tracing in resolvers during development? Couldn't find anything in the docs.

Thx

**Comment by rafalp** [comment]
Exceptions raised in resolver during query execution being caught and repackaged into GraphQL responses is part of [GraphQL-core-next](https://github.com/graphql-python/graphql-core-next), a GraphQL implementation library that Ariadne uses.

I am not aware of a way for preserving tracebacks on those for debugging other than maybe implementing custom middleware in Ariadne that would catch and log those before reraising exception for regular flow.

**Comment by ceelian** [comment]
Thx, opened an issue on their repository: https://github.com/graphql-python/graphql-core-next/issues/23

**Comment by rafalp** [comment]
I'm reopening this because I feel Ariadne should have an answer to this problem.

Quick peek around `graphql.execution.execute` shows that original exception that causes `GraphQL` error is available on the `result.error.original_error`. Offering traceback as part of response could be doable in Ariadne via `graphql.execution.execute.__traceback__`, but this will require some checking.

**Comment by ajhyndman** [comment]
Happy update: It looks like `graphql-core-next` has published an upstream fix for this issue!

Thanks for following through, @ceelian .
