### ISSUE TITLE
execution_context_class argument for graphql_sync raises an error

### ISSUE THREAD

**Issue by DenMesh** [mirumee/ariadne#1131]
As stated in the title. I am trying to follow the docs for sync dataloaders, which requires a different execution context class than the default. However, this raises a TypeError:
```
graphql_sync(<some_irrelevant_args_and_kwargs>, execution_context_class=DeferredExecutionContext)
```
I've checked the code and the reason is line 190 in graphql.py, which explicitely sets execution_context_class.

**Comment by DenMesh** [comment]
I will check for code updates before posting.

**Comment by rafalp** [comment]
Can you please explain? Is this issue with Ariadne or something on your side?

Thanks!

**Comment by DenMesh** [comment]
My side. My version of Ariadne was a couple releases behind, thus lacking the ability to override execution_context_class. An update solved the issue.

**Comment by rafalp** [comment]
Excellent, thanks for clarifying!
