### ISSUE TITLE
Subscription Chat Application full example does not return message data

### ISSUE THREAD

**Issue by alico-cra** [mirumee/ariadne#1133]
Following the example subscription app provided here: https://github.com/mirumee/ariadne-graphql-chat-example 
It appears that the object being yielded back is returning data as null. 
The query goes through the resolver as expected and logging the content before it yields contains the correct data.

I am using local memory for communication, and the Broadcast package.

```
broadcast = Broadcast("memory://")

mutation = MutationType()

@mutation.field("send")
async def resolve_send(*_, **message):
    print("Send", message, json.dumps(message))
    await broadcast.publish(channel="chatroom", message=json.dumps(message))
    return True

subscription = SubscriptionType()

@subscription.source("message")
async def source_message(_, info):
    async with broadcast.subscribe(channel="chatroom") as subscriber:
        async for event in subscriber:
            print("Event", event, event.message)
            yield json.loads(event.message)
```

```
app = Starlette(
    debug=True,
    on_startup=[broadcast.connect],
    on_shutdown=[broadcast.disconnect],
)
# Mount app to handle GET and POST methods
app.mount("/graphql/", graphql)

# Mount app to handle websocket connections
app.add_websocket_route("/graphql/", graphql)
```

![image](https://github.com/mirumee/ariadne/assets/115261150/fb81c55c-9fea-40b1-ae03-d4e7c7537ad1)

![image](https://github.com/mirumee/ariadne/assets/115261150/dfe09298-a9a5-4d7d-ad29-aa54b66a2b2d)

Is this a GraphiQL issue? Or perhaps an issue with using local memory as opposed to something like redis?

**Comment by rafalp** [comment]
Hey, thanks for reporting. I'll investigate.

**Comment by rafalp** [comment]
This seems to be an issue with local memory storage. The setup that repo uses is working without any changes, even GraphiQL subscribes to updates:

<img width="1722" alt="Zrzut ekranu 2024-01-26 o 14 01 55" src="https://github.com/mirumee/ariadne/assets/750553/a86b4d94-2471-4283-be30-deab109be50d">
