### ISSUE TITLE
"str" is incompatible with "GraphQLSchema"

### ISSUE THREAD

**Issue by khanakia** [mirumee/ariadne#1135]
I am using below example and getting the error
```
Argument of type "str" cannot be assigned to parameter "schema" of type "GraphQLSchema" in function "__init__"
  "str" is incompatible with "GraphQLSchema"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
(variable) schema: str
```

```py
from ariadne.asgi import GraphQL
from ariadne import gql, load_schema_from_path

# from gql import schema

schema = gql("""
  type Query {
    user: User
  }

  type User {
    id: ID
    username: String!
  }
""")


app = GraphQL(schema, debug=True)
```

![Screenshot 2023-11-19 at 8 31 05 PM](https://github.com/mirumee/ariadne/assets/2174170/b3aa4b7c-f031-4162-b27b-3187988c86f8)

**Comment by rafalp** [comment]
Hello, where did you find this example?

**Comment by khanakia** [comment]
I copied it from the homepage https://ariadnegraphql.org/

Instead of telling `schema = load_schema_from_path("schema.graphql")` it schema we should call it `type_defs` so user won't get confused.

I was able to fix by calling the `make_executable_schema` functions
