### ISSUE TITLE
Add support for `@oneOf` input objects

### ISSUE THREAD

**Issue by DamianCzajkowski** [mirumee/ariadne#1194]
### Discussed in https://github.com/mirumee/ariadne/discussions/1193

<div type='discussions-op-text'>

<sup>Originally posted by **steve-marmalade** August 21, 2024</sup>
It looks like the community has landed on a solution for describing a "union of inputs" in a GraphQL schema: https://github.com/graphql/graphql-spec/pull/825

I'd love to use this in my Ariadne server. Does that PR demonstrate enough momentum around the feature to consider implementing it?</div>

**Comment by rafalp** [comment]
As @upcFrost says in that discussion, this will have to be done by the [graphql-core](https://github.com/graphql-python/graphql-core) folk and not Ariadne - we rely on GraphQL core dependency for actual GraphQL implementation and mostly wrap it with servers and convenience features.
