### ISSUE TITLE
Support content type "application/graphql"

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#121]
> If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

**Comment by thebenwaters** [comment]
@rafalp going to try and tackle this in the next few days

**Comment by rafalp** [comment]
Note to self: check if this is still the case for GraphQL servers in 202X

**Comment by rafalp** [comment]
> Note to self: check if this is still the case for GraphQL servers in 202X

I've did a search for this feature's popularity in the wild and it seems to be a de facto dead part of spec. Only argument I've found for it being available is the ease of typing GraphQL requests in CURL. Arguments against it are JSON being widespread in clients, and missing support for variables as separate payload.

We aren't going to do this, but if somebody creates a pull request that adds it, and this PR passes review, we'll merge it.
