### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by karthikmurali** [mirumee/ariadne#127]
Hi,

When will you be releasing to pypi next? Currently the examples/doc don't match the version in pypi - thanks!

**Comment by rafalp** [comment]
Hello,

Can you please explain how docs and examples don't match the version on pypi? Our docs are and examples versioned together with releases, so you can always see the docs for version you are using.

**Comment by karthikmurali** [comment]
This fails with a TypeError;

# Run a dev server that includes GraphQL Playground
start_simple_server(schema) # Visit http://127.0.0.1:8888 to see the API explorer!

In the pypi version start_simple_server is called like so
start_simple_server( type_defs, query)

I will use the pypi docs , thanks

**Comment by rafalp** [comment]
Docs kept on the repository are always under active development. Please use docs hosted on read the docs instead. Same applies for readme: current readme is one of Ariadne's PYPI page. ;)

We want to release latest changes as Ariadne 0.3 soon.
