### ISSUE TITLE
Relay implementation

### ISSUE THREAD

**Issue by Zorig** [mirumee/ariadne#188]
Is there any plan to implement relay on top of it? If not, how can i implement relay on it?

**Comment by rafalp** [comment]
Hello!

To implement Relay support in your GraphQL server, you simply need to design [your schema in a certain way described on Relay documentation](https://facebook.github.io/relay/docs/en/graphql-server-specification.html). There is no extra work required to do in Ariadne to make it work.

I know that Graphene provides built-in types for relay objects, but that makes sense for them because in Graphene schema is generated from Python types. Ariadne is schema-first library, so it is on the developer to include `Node`, `Edge` and `Connection` types that Relay uses in their GraphQL schema.

This could potentially be explained by our documentation, so I'll keep this issue open.

Thanks!

**Comment by Zorig** [comment]
@rafalp thanks for the response, well, then if I define my schema according to relay documents then   about resolvers, like ariadne's resolver works fine? Or do I have to define resolver differently? I mean is decorator works fine? I saw that graphql-relay-py uses interface and such things hence little bit confused

**Comment by rafalp** [comment]
You will have to write your own resolvers for `ID` fields and `Connection` types. Decorator is only how you tell Ariadne that your function is resolver for something. You will need to write the function yourself.

**Comment by patrys** [comment]
I think we could provide some `dataclass` objects and interface implementations to automate the connection object resolution? Example:

```
def resolve_book_authors(book: Book, info, *, first: int, after: str):
    ...
    authors = ...
    return Connection(authors, page_info=PageInfo(...))
```

**Comment by Zorig** [comment]
@rafalp @patrys do i have to define schema like `graphql-relay-py`'s test [schema](https://github.com/graphql-python/graphql-relay-py/blob/master/tests/starwars/schema.py) ? or just a plain `type SomeConnection, typeSomeEdge` like official relay [docs](https://facebook.github.io/relay/docs/en/graphql-server-specification.html)

**Comment by patrys** [comment]
Just follow the official Relay docs. The tricky part is implementing the Node interface on `Query.node` as it requires that you're able to detect the type of object to return based on the `ID` alone. It requires your `ID` to either encode the object type (Graphene uses `base64(object_type + ":" + object_pk)`) or to be globally unique.

**Comment by rafalp** [comment]
I've did quick and ugly implementation for supernaive GraphQL API that lists spaceships using relay format. It came out more complex than I've expected, so I am now leaning on inclusion of `ariadne.contrib.relay` package in the future.

Here's the code for those interested. API runs, but I don't guarantee that its actually 100% compliant with Relay's spec:

```python
import base64
from dataclasses import dataclass

from ariadne import InterfaceType, ObjectType, QueryType, make_executable_schema
from ariadne.asgi import GraphQL


@dataclass
class Ship:
    id: int
    name: str


ships = [
    Ship(1, "Kuun-Lan"),
    Ship(2, "Faal-Corum"),
    Ship(3, "Clee-San"),
]


def get_relay_node_id(obj):
    # Returns relay ID
    # You will have to provide actual implementation for obj.id yourself!
    return base64.b64encode(
        "{}:{}".format(type(obj).__name__, obj.id).encode("utf-8")
    ).decode("utf-8")


def get_relay_node_cursor(position):
    # Returns relay cursor for position
    # You will have to provide actual implementation for obj.id yourself!
    return base64.b64encode(
        "arrayconnection:{}".format(position).encode("utf-8")
    ).decode("utf-8")


type_defs = """
    interface Node {
        id: ID!
    }

    type Ship implements Node {
        id: ID!
        name: String
    }

    type ShipConnection {
        edges: [ShipEdge]
        pageInfo: PageInfo!
    }

    type ShipEdge {
        cursor: String!
        node: Ship
    }

    type PageInfo {
        hasNextPage: Boolean!
        hasPreviousPage: Boolean!
        startCursor: String
        endCursor: String
    }

    type Query {
        ships: ShipConnection!
    }
"""


relay_node = InterfaceType("Node")


@relay_node.type_resolver
def resolve_relay_node_type(obj, *_):
    # Very simple implementation that will break if resolvers return dicts
    # intead of objects
    return type(obj).__name__


@relay_node.field("id")
def resolve_relay_node_id(obj, *_):
    return get_relay_node_id(obj)


query = QueryType()


@query.field("ships")
def resolve_ships(*_):
    # Dummy relay result - 
    return {
        "edges": [
            {
                "cursor": get_relay_node_cursor(position),
                "node": ship,
            } for position, ship in enumerate(ships)
        ],
        "pageInfo": {
            "hasNextPage": False,
            "hasPreviousPage": False,
            "startCursor": get_relay_node_cursor(0),
            "endCursor": get_relay_node_cursor(len(ships) - 1),
        }
    }


schema = make_executable_schema(type_defs, [query, relay_node])

app = GraphQL(schema, debug=True)
```

**Comment by patrys** [comment]
Please note that it's a very bad idea to base your pagination cursors off `LIMIT`/`OFFSET`-style queries. An efficient pagination query would use the `after` (or `before`) value in the `WHERE` clause:

```sql
SELECT ship.id, ship.name
FROM ship
WHERE ship.id > "lastSeenIdFromThePreviousPage"
ORDER BY ship.id
LIMIT 10
```

**Comment by andreasnuesslein** [comment]
This had a `decision needed` label now for 9 months or so. Are there plans to implement this as `ariadne.contrib.relay`?

Cheers :)

**Comment by rafalp** [comment]
Hiya @andreasnuesslein, thanks for bringing this back up.

I don't think that `ariadne.contrib.relay` is likely to ever happen, but reason for this is not that we are against Relay or utilities for it in Ariadne. It's just that we can't invest into developing and maintaining it ourselves.

If somebody else was to develop package named `ariadne-relay` or such, they have our support. We'll be more than happy to mention it  in our docs and would point people using Relay to it.

Thanks for understanding!

**Comment by andreasnuesslein** [comment]
@rafalp Thank you for your answer. 
Can you tell me how you go about pagination then? (I hope I didnt overlook something in the docs)

**Comment by rafalp** [comment]
@andreasnuesslein just do whatever works for you  ¯\_(ツ)_/¯ 😁

No, really. Relay is opinionated GraphQL client, but Apollo-Client is not, so you can create custom type representing list page (or feed fragment):

```
type Query {
    posts(start: String): PostsFeed
}

type PostsFeed {
    posts: [Post!]!
    nextStart: String
}

type Post {
    id: String!
    content: String!
}
```

Or for ol' offset pagination (say, for Django `Pagination`):

```
type Query {
    posts(page: Int): PostsPage
}

type PostsPage {
    items: [Post!]!
    next: Int
    previous: Int
}
```

**Comment by andreasnuesslein** [comment]
@rafalp Thank you :)

**Comment by markedwards** [comment]
@rafalp I've built a stable implementation for connections, based on a decorator that wraps an `ObjectType` resolver that emits a `Sequence`.  The implementation resolves the connection using [graphql-relay-py](https://github.com/graphql-python/graphql-relay-py).
As you say, I think the right path forward here is to build an `ariadne-relay` package, and it seems reasonable to build that on top of **graphql-relay-py** so it adheres closely to [Relay](https://github.com/graphql/graphql-relay-js) itself.  Suppose this module provided a `ConnectionType` subclass of Ariadne's `ObjectType`, and other Relay types in the same pattern?
I might be willing to own development of this, but I haven't completely thought it through yet.  It's just an idea.
