### ISSUE TITLE
Should EnumType accept internal values when using enum.Enum?

### ISSUE THREAD

**Issue by ajhyndman** [mirumee/ariadne#200]
This is a little subtle, so let me see if I can make it clear enough to get the point across.

Currently, if you use `EnumType` and pass an `Enum` class as the value mapping, the behaviour isn't exactly what I expected.

I have tried creating an enum class that maps from GraphQL enum names to the internal string values used by our server.

```python
class TeamType(enum.Enum):
  ORG = 'org'
  MANAGER = 'manager'

team_type = EnumType('TeamType', TeamType)
```

By reading Ariadne's implementation, I can see that one of my resolvers receives a value which is an instance of Enum value (i.e. `TeamType .ORG`), then Ariadne will correctly transform that and return the associated enum value's name.  However, if my resolver receives the actual _string_ value we used when defining the `TeamType` enum, then Ariadne does not recognize that value, and will throw a GraphQLError.

Of course, this can be worked around trivially, using a dictionary instead of `Enum`.

```python
team_type = EnumType('TeamType', {'ORG': 'org', 'MANAGER': 'manager'})
```

But it feels like a bit of a rough edge to me.  Or it might limit the utility of supporting Enum to define transformation.  Thoughts?

**Comment by rafalp** [comment]
Looks like a BUG to me. `{ myField(enum: ORG) }` should pass `TeamType.ORG` to the python resolver, and resolver returning the `TeamType.ORG` should result in `ORG` appearing in the query result.

**Comment by ajhyndman** [comment]
@rafalp To clarify:

If a resolver returns `TeamType.ORG`, then `'ORG'` correctly appears in the query result.

What I wasn't expecting (but maybe is okay?) was that if the resolver returns `'org'`, then the resolver throws a validation error, instead of `'ORG'` appearing in the query result.

**Comment by rafalp** [comment]
So long story short, `Enum.ORG` is not equal to `org`. You need to update your enum definition:

```
class TeamType(str, enum.Enum):
  ORG = 'org'
  MANAGER = 'manager'
```

That will fix it.

**Comment by ajhyndman** [comment]
@rafalp Oh cool.

That definitely solves my use case.  Thank you for investigating!
