### ISSUE TITLE
Writing tests for resolvers?

### ISSUE THREAD

**Issue by qoonqode** [mirumee/ariadne#206]
How do we go about writing tests for our resolvers with this library? 

Graphene has a test client for this purpose, but I didn't see anything in the documentation regarding testing functionality.   I'm pretty new to QA, but I want to be able to write tests for my code, and I didn't know how I was supposed to go about this with Ariadne.

Any insight would be great here.   :)

**Comment by rafalp** [comment]
You can go about it using either of those approaches:

- Use test client provided by your web stack (or framework) to make `POST` request to your GraphQL's URL with `{"query": "{ testQueryHere }"}` JSON. This tests integration for the entire stack and resolver tree.
- Unit test your resolver functions and mock `info` together with the rest of resolver's arguments.

Combination of both will likely be best approach, but privately I am sticking to the first one.

**Comment by qoonqode** [comment]
That makes sense, I think.   

The only thing I might be confused about is how I would go about testing stuff like DB operations (for instance, writing a test for a resolver that creates a new user), but...maybe that's just some stuff I need to learn about testing in general?

Anyway, I appreciate the response a lot.   I think I probably have a lot to learn.  :P

Either way, as someone new to Python and web stuff, I really am liking how straightforward this library seems to be, so thanks a lot for it!

**Comment by patrys** [comment]
To add to @rafalp's response, I would avoid testing resolvers over HTTP. If you have a schema, it's usually better to test using `graphql` or `graphql_sync` instead of spawning an HTTP server.

https://ariadnegraphql.org/docs/api-reference#graphql
https://ariadnegraphql.org/docs/api-reference#graphql_sync

**Comment by rafalp** [comment]
Yeah, speaking about test client I've had on mind test clients that just run your GraphQL view logic without spinning http server beneath - like how Django test client does it. I'll assume its the same for Starlette?

**Comment by qoonqode** [comment]
I think this is actually what I was looking for.    I just hadn't read the docs enough, apparently!

What's the proper way to test stuff that interacts with a database?  I would assume that in this case, you're supposed to use mock objects (if you're testing queries and fetching data), but what about storing it?

I guess that's probably outside the scope of this project, but I also don't know how some of this stuff works.   I'm sure I'll figure it all out, though.

**Comment by patrys** [comment]
In an ideal world, your logic lives in a separate layer from your resolvers and resolvers are only a mechanism to pass data between input, logic, and output. If you separate data loading and storage from actual processing, you should be able to mock the database part without disabling any of the processing parts.

**Comment by dkbarn** [comment]
Does anyone know how to measure and report the percentage of the schema that is being touched by tests? Test coverage is not ideal because it can only report on lines of code reached -- it wouldn't help if for example you introduced a new field to your schema and forgot to write a resolver for it.

I guess I'm wondering if there's a way to measure the "schema coverage" of your tests. Any tips for how to do this?

**Comment by bartenra** [comment]
@dkbarn You can use this GraphQL CLI plugin: https://www.npmjs.com/package/@graphql-cli/coverage

Example:

![image](https://user-images.githubusercontent.com/77667589/122019322-f228a980-cdc3-11eb-829f-0edc297d6eea.png)
