### ISSUE TITLE
Example not working [similar to #177]

### ISSUE THREAD

**Issue by saern** [mirumee/ariadne#210]
Using Ariadne==0.5.0 and Uvicorn==0.8.3, following the example on [https://ariadnegraphql.org/docs/django-integration](url), where it is in a list called `http_routes`, and used in a ProtocalTypeRouter:
```
http_routes = []
http_routes.append(path("graphql/", GraphQL(schema, debug=True)))

router = ProtocolTypeRouter({
    "http": URLRouter(http_routes),
    "channel": ChannelNameRouter({
        "channelone": ChannelOneConsumer
    })
})
```

When Apollo-Federation calls this endpoint, I get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
    instance = self.app(scope)
  File "/usr/local/lib/python3.7/site-packages/channels/routing.py", line 58, in __call__
    return self.application_mapping[scope["type"]](scope)
  File "/usr/local/lib/python3.7/site-packages/channels/routing.py", line 144, in __call__
    "kwargs": {**outer.get("kwargs", {}), **kwargs},
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
[2019-07-04 11:54:07 +0800] [497] [INFO] ('172.21.0.3', 50320) - "POST /graphql/ HTTP/1.0" 500
```

The comment [https://github.com/mirumee/ariadne/issues/177#issuecomment-493950544](url) says that Ariadne should be using ASGI3, but uvicorn still shows to be using ASGI2? (`uvicorn/middleware/asgi2.py`).
Btw I am using channels==2.2.0
What should I do to get around this?

**Comment by saern** [comment]
My bad, I misread part of the documentation about using `as_view`.

**Comment by patrys** [comment]
I think you may be confusing two separate integrations, one for Django and one for Django Channels. You should only use one of them. Django Channels integration is currently broken as we're waiting for an ASGI3 version of Channels.

Here's a workaround ASGI2 compatibility class that you can use instead of `ariadne.asgi.GraphQL` if you want to use it:

```python
from ariadne.asgi import GraphQL

class DjangoChannelsGraphQL(GraphQL):
    def __call__(self, scope) -> None:
        async def handle(receive, send):
            await super(DjangoChannelsGraphQL, self).__call__(scope, receive, send)
        return handle
```

**Comment by hvdklauw** [comment]
I've been going over my code again and again but even with the mentioned change this does not work correctly.

As soon as I query a subscription the websocket opens and the server accepts no further connections.

So any other query or mutation I would want to execute just hangs.

Now I have a current working graphql subscription setup with django-channels-graphql-ws that does not have this issue.
It seems for the correct django channels implementation we need a Channels consumer in between or something.

**Comment by patrys** [comment]
You do not need any consumers. Do remember that if you use the ORM you have to do it in code [decorated with `database_sync_to_async`](https://channels.readthedocs.io/en/latest/topics/databases.html#database-access), otherwise the ORM will block the event loop.

**Comment by hvdklauw** [comment]
Oh man.. it wasn't the database part, it was the redis connection that was my issue... switched to aioredis and it all works..

**Comment by saern** [comment]
I've been extremely busy, over the next few days I should have a chance to implement your solution and see how it works for me, as I'm not using websockets nor Django's ORM.

**Comment by rafalp** [comment]
Closing this as answered. If there are any other questions, feel free to ask!
