### ISSUE TITLE
Recommended way to wrap mutation in a transaction

### ISSUE THREAD

**Issue by alexchamberlain** [mirumee/ariadne#211]
What is the recommended way of wrapping a mutation in a transaction? I can think of 2 alternatives:
1. Create a middleware that detects if it is at the top of the mutation; if so, manage the transaction, otherwise pass through doing nothing.
2. Create a custom `graphql.ExecutionContext` that overrides the `execute_operation` method. I can't figure out how to pass a custom `execution_context_class` into asgi.GraphQL, however.

**Comment by rafalp** [comment]
Can you describe what you are trying to accomplish here? The simplest way to put mutation into a transaction would be to create this transaction inside mutation's resolver function.

But if you are trying to bunch few mutations into a single transaction, this is an anti-pattern in GraphQL* - you should create a single mutation that combines behaviour of those into one.

* (because spec requires that fields on same depth will be resolved independently from each other).

**Comment by alexchamberlain** [comment]
I was trying to do 2 things:
- Make transaction handling independent of the resolver functions. For example, I want to run a `SET SESSION` command on the postgres instance.
- To be honest, I would like to bunch a few mutations into a single transaction. I thought mutations had to be executed serially in the order given? I guess that is orthogonal to independence though.

**Comment by rafalp** [comment]
> I thought mutations had to be executed serially in the order given?

They are, but this is only so the potential for race conditions between each other is reduced.

> To be honest, I would like to bunch a few mutations into a single transaction

Yeah, this goes against the grain. With GraphQL you are supposed to have your types and mutations as close to the business process and avoid using it as a low-level database interface, which also leads to thin resolvers merely calling business logic that's located elsewhere in your application code.

**Comment by patrys** [comment]
To add to that, only the top-level resolver is supposed to modify the state of the application, its fields are regular read-only resolvers to fetch the results of the mutation. This means you should not try to "namespace" mutations by putting side effect-bearing resolvers inside another resolver.

**Comment by alexchamberlain** [comment]
Ok, thanks for the advice. I'll just write a `transaction` decorator to factor out the repetitive transaction code.
