### ISSUE TITLE
Case conversion in arguments and field names

### ISSUE THREAD

**Issue by smaaland** [mirumee/ariadne#212]
When using the `snake_case_fallback_resolvers` I can properly resolve snake_case variables in my application. But is there any way to make field names, arguments, query variables and such into snake_case as well? I think it's not very pythonic to get camelCase'd arguments into my python resolver functions. 

It seems that camelCase is the proper way to do it in the schema, but it's not very nice in python code.

**Comment by rafalp** [comment]
We've been contemplating the creation of decorator for that, something like this:

```
@convert_kwargs_case
def resolve_login(_, info, *, date_of_birth):
    ...
```

I guess such util should perform the cache conversion recursively, so inputs and lists of objects are converted too?

**Comment by smaaland** [comment]
Yes, I think that would be pretty good as a simple first solution.

But preferably it should maybe happen in an earlier stage than that even, so that we can use a proper snake case variable in query- and field decorators etc. (or just anywhere inside Ariadne where we reference any type of fields etc.). Somewhere after schema validation happens (since the schema should probably be case agnostic anyway)?

**Comment by rafalp** [comment]
Potentially you could create a bindable that applies this decorator to resolvers on all fields that specify arguments.

**Comment by smaaland** [comment]
I created a pull request for this now: https://github.com/mirumee/ariadne/pull/213
