### ISSUE TITLE
Possible to check for requested output in resolver

### ISSUE THREAD

**Issue by tbsf** [mirumee/ariadne#218]
Is it possible to check what is being requested in the resolver for a query? For example, if I have the following schema:

```javascript
type Query {
    getUser(username: ID){
        email: String
        phone: String
    }
}
```

Can I create a resolver like this?

```python
...
@query.field("getUser")
def get_user(obj, info, username):
    requested_data = ... # This is what I'm looking for
    response = {}
    if "email" in requested_data:
        response["email"] = get_email(username)
    if "phone" in requested_data:
        response["phone"] = get_phone(username)
    return response
```

**Comment by rafalp** [comment]
`info` argument is an instance of [`GraphQLResolveInfo`](https://github.com/graphql-python/graphql-core-next/blob/v1.0.5/graphql/type/definition.py#L487). The `info.field_nodes` contains what you are looking for.

**Comment by tbsf** [comment]
Something like` _request.field_nodes[0].selection_set.selections`? Is that the only way?

**Comment by patrys** [comment]
@tbsf Not sure what you're trying to do but consider:

```python

def foo_resolver(root, info):
    fields = {f.name for f in info.field_nodes}
    # print(fields)
```

**Comment by rafalp** [comment]
Closing this one. Feel free to ping me back @tbsf if you feel there's something else to add. Potentially we could have a guide on our docs showing how one can introspect which fields are asked in resolver to, say, eagerly fetch data needed in child resolver

**Comment by andreasnuesslein** [comment]
Adding some information for other people that stumble here:

First of all, this is probably what you're looking for:
```python
for field_node in info.field_nodes:
    print([f.name.value for f in field_node.selection_set.selections])
```

"Why the loop around the inner (more obvious) loop" you might ask..

Taking this example
```graphql
query {
  getUsername(id:2) {
    email
    phone
  }
  getUsername(id:2) {
    phone
  }
  getSomethingElse(id:5) {
    field_a
    field_b
  }
}
```

```python
def getUsername(obj: Any, info: GraphQLResolveInfo):
    for fnode in info.field_nodes:
        print([f.name.value for f in fnode.selection_set.selections])
```

will output:
```
['email', 'phone']                                                                                                                                                          
['phone']
# but not 
['field_a', 'field_b'] # from getSomethingElse
```

Which a) is kinda efficient - Ariadne doesn't call the `getUserName` twice but rather once with all the required arguments and b) means only the `field_nodes` that actually map to `getUserName` are in this list.
