### ISSUE TITLE
Resolving a related field inside a Django model

### ISSUE THREAD

**Issue by isopterix** [mirumee/ariadne#231]
I was playing around with the library (AWSOME WORK BTW!!!) and tried to expose a related field of a foreign key relationship between two Django model objects.

While the regular model fields are resolved perfectly, the related object throws a type error:
**TypeError: __call__() takes 1 positional argument but 2 were given**

Here are my two related tables:
```python
class KpiTarget(models.Model):
    kpi = models.ForeignKey(Kpi, on_delete=models.CASCADE)
    ...
    validFrom = models.DateField()

    def __str__(self):
        return str(self.kpi)

class KpiObservation(models.Model):
    kpiTarget = models.ForeignKey(KpiTarget, on_delete=models.CASCADE)
    observationBool = models.BooleanField(blank=True, null=True)
    observationStr = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return str(self.observed)
```

The Schema
```graphql
type Query {
  kpiTargets(site: ID): [KpiTarget]
}

type KpiTarget {
  id: ID!
  kpi: Kpi
  [...]
  validFrom: Date
  kpiobservation_set: [KpiObservation] <<---- obtaining this field triggers the error
}

type KpiObservation {
  id: ID!
  kpiTarget: KpiTarget
  observationBool: Boolean
  observationStr: String
}
```

My resolver:
```python
@query.field("kpiTargets")
def resolve_kpiTargets(*_, site=None):
    if site:
        return KpiTarget.objects.filter(site=site)
    else:
        print(KpiTarget.objects.get(id=3).kpiobservation_set)
        return KpiTarget.objects.all()
```

Is this expected behavior?

**Comment by rafalp** [comment]
Hey!

Did you define the resolver for `KpiTarget.kpiobservation_set`? If not, then that field will be resolved by default resolver, and that one doesnt work with for django related fields.

**Comment by isopterix** [comment]
I was already kind of suspecting it. But then again I don't really have a clue how I get this resolver to work. First step was to just try to get the custom resolver triggered when accessing this field. But I cant even get that to work. It will always take the default resolver - I guess from the query resolver function. The field resolver is ignored.

```python
kpiTarget = ObjectType("KpiTarget")

@kpiTarget.field("kpiObservationSet")
def resolve_related_field(obj, info):
    print("Hurray!!!")
```

**Comment by rafalp** [comment]
All `ObjectType` items need to be passed to `make_executable_schema`, not just `query`:

```python
schema = make_executable_schema(types, [query, kpiTarget, ...])
```

**Comment by isopterix** [comment]
Sorry, had missed that. Let's see if I get it sorted now... Thanks!

**Comment by isopterix** [comment]
Got it working! Cool stuff!
