### ISSUE TITLE
Using middleware to deny general API access to all non-authenticated users, except login mutation and schema

### ISSUE THREAD

**Issue by isopterix** [mirumee/ariadne#236]
Still exploring this library... I wanted to setup a default behavior which denies access for non-authenticated users to any resolvers not specified in a given list.

The way I implemented this was using the GraphQL middleware function as explained in the docs.

This has worked, but unfortunately, now the schema introspection queries are also denied :) This is obviously not really what I wanted.

How would I go about this? I tried to identify the "technical" queries from the provided arguments in the Middleware layer... e.g. using the path. But that only works for the first layer.

```python
list_of_exempted_resolvers = ['resolve_login',]

def login_required_middleware(resolver, obj, info, **args):
	path = info.path
	proceed_with_request=False

	# check if requested resolver is in exempted list of resolvers
	if resolver.__name__ in list_of_exempted_resolvers:
		proceed_with_request=True
		print("exempted request")

	# ignore technical fields (e.g. used for introspection)
	if isinstance(path.key, str) and path.key.startswith("__"):
		proceed_with_request=True
		print("technical request")
	
	# enforce auth access policy
	if proceed_with_request:
		print("continue")
	else:
		# only proceed with request if user is logged-in. Otherwise raise error instead.
		print("objections exist")
		if not info.context.user.is_authenticated:
			raise ValueError ("FORBIDDEN: User is NOT AUTHENTICATED. Please login first, and try again.")
	
	# if no objections return resolver result
	print("resolve")
	return resolver(obj, info, **args)
```

I initially had setup the "login_required" requirement using a custom decorator. But in my case this would need to go on each resolver other than the "login" mutation. I figured this is a bit redundant, hence I was wondering is there is a better more generalist approach to this.

**Comment by isopterix** [comment]
btw... this was my custom decorator before...

```python
def login_required(f):
    def wrapper(obj, info, *args, **kwargs):
        if info.context.user.is_authenticated:
            return f(*args, **kwargs)
        else:
            raise ValueError ("FORBIDDEN: User is NOT AUTHENTICATED. Please login first, and try again.")
    return wrapper
```

**Comment by rafalp** [comment]
In Ariadne 0.6 there's `is_introspection_field` util that allows you to check if a field is part of introspection: [`is_introspection_field`](https://github.com/mirumee/ariadne/blob/master/ariadne/contrib/tracing/utils.py#L26)

...but IMHO field authentication is a perfect use case for schema directives, and we want to deliver support for those soon-ish: #222

In the meantime, I would consider resolver decorator a better alternative to the middleware. Middlewares fire for all resolvers by default, so your exclusion list will have to be extended every time you add a new field, or your middleware updated to pass-trough resolvers for fields deeper than root ones... until there's sub-field that wil also need to be behind the auth - those things will add up quickly ;)

**Comment by isopterix** [comment]
Thanks @rafalp! Good point. The fireing for each field is really prohibitive. I was not aware of that until I did some more testing.

Looking forward to the additions of directives then. Unfortunately, my python is not good enough to make any useful contributions, yet.
