### ISSUE TITLE
default resolver for Query

### ISSUE THREAD

**Issue by salvador-immortal** [mirumee/ariadne#237]
hi , im trying to create resolver for my Types . ..
should i always first define resolver for RootQuery Field ?

my Code:

```
from ariadne import QueryType, make_executable_schema, ObjectType
from ariadne.asgi import GraphQL

type_defs = """
    type Query {
        user: User
    }
    type User {
        username: String
        fullname: String
    }
"""


query = QueryType()
user = ObjectType('User')

@query.field('user')
def resolve_user(_,info,**kwargs):
    return 'something'

@user.field("username")
def resolve_username(_, info, **kwargs):
    request = info.context["request"]
    user_agent = request.headers.get("user-agent", "guest")
    return "Hello, %s!" % user_agent

schema = make_executable_schema(type_defs, [query,user])
app = GraphQL(schema, debug=True)
```
the `resolve_username` is not working when i remove `resolve_user` th binded to Query
and also `resolve_username` doesnt work when i just `pass` the resolve_user

needed more Examples for Modularization in Doc .

**Comment by rafalp** [comment]
Hello!

Could you describe what your API is supposed to do? I've looked at your code but it seems to be mixing two different examples so it's not clear to me. Thanks!

**Comment by salvador-immortal** [comment]
@rafalp 
im creating normal user type , i wanna to create a simple blog app . .
yeah this example is very basic .. and not complete yet (user fields just should return string and something like that)

first of all ,, i discovered if i dont add `User` Type to `Query` fields.. i can not use my User schema ,,am i right ? then i added `user` to Query type as field .

after that i tried to create some resolvers for my user type .. and before creating `resolve_user` (@query.field('user')) ,, my user fields resolvers were not available ,, and querying this :
```
{
   user {
          username
          fullname
     }
}
was returning `null`

**Comment by patrys** [comment]
@salvador-immortal  That's how GraphQL works: if any of the parent resolvers (in your case the `user` resolver on the `Query` type) returns `NULL`, query resolution won't go any deeper. You have to either define a user resolver or provide a `root_value` that includes a value for the `user` field (so the default resolver returns it).

In your case, the logic should probably live in the `Query.user` resolver and not in the `User.username` resolver. Consider:

```python
query = QueryType()

@query.field('user')
def resolve_user(_, info, **kwargs):
    request = info.context["request"]
    user_agent = request.headers.get("user-agent", "guest")
    username = "Hello, %s!" % user_agent
    return {
        "username": username,
        "fullName": "whatever",
    }
```

In this case, you can skip defining any resolvers for the `User` type as the default resolver will see a matching key in the dictionary returned by `resolve_user` and use it when `username` is requested.

**Comment by salvador-immortal** [comment]
@patrys 
thanks alot , you explained very well 
but one more question

if i have alot of types (ex: `user` , `post` , `comments` , ... etc) .. should i define all `resolvers` on `Query` like that you wrote? 
(i know i can use `set_field` for spliting things ,, but it seems lots of codes and efforts for creating dict objects of all fields(coupling), and dependency on `Query` ,, 
if it was smart to just define `user: User` on `Query` and automatically `resolvers` of `user` (like i wrote `resolve_username` assigning to `user` of `Query` , i think it whould be good ..  )

BTW , thanks

**Comment by patrys** [comment]
In a large application, you'd typically define resolvers, data loaders, and other helpers in their own specific modules and import their particular lists of resolvers and type definitions in one place where you combine the schema. You can also use the `extend type ...` syntax to add the module-specific fields to different types (including `Query`).

**Comment by rafalp** [comment]
Closing this as resolved. If you need anything else @salvador-immortal, please ping us here or on our [spectrum chat](https://spectrum.chat/ariadne)
