### ISSUE TITLE
Exceptions are never delivered to extensions

### ISSUE THREAD

**Issue by smaaland** [mirumee/ariadne#242]
If you add an extension that implements the `def request_finished(self, context: ContextValue, error: Optional[Exception] = None)` method, and raise any kind of Exception in the resolver, the `request_finished` method of the extension always gets called without any errors.

A stack trace shows that the request context manager in `extensions.py` never catches the exception, so the `else` statement is always executed no matter what kind of exception I raise.

**Comment by patrys** [comment]
This signature looks bad, all exceptions are handled by the executor so `errors` would have to be a list since technically all resolver can raise without preventing execution of the rest of the query.

**Comment by rafalp** [comment]
Yup, that one is not going to work, but we have `Extension.has_errors()` that will be called with a list of errors by our error/response handlers.

**Comment by rafalp** [comment]
So, I've created the #246 PR where `error` arg is removed from `request_finished()` hook.

I've also started thinking about `has_errors` hook, which is called with the `result.errors` value, but to access the `context` value in it, one has to store reference to it in a different hook (eg. in `request_started`):

```python
class MyExtension(Extension):
    def __init__(self):
        self.context = None

    def request_started(self, context):
        self.context = context

    def has_errors(self, errors):
        ... # do comething with both errors and context
```

I'm contemplating now how we should go about it. We could update the `handle_query_result` and `handle_graphql_errors` to take `context` in addition to `extension_manager`, but I feel we could update our `ExtensionManager` to take `context` as extra argument, so we will be able to call hooks with it without reliance on passing those from hook's call place. Ergo:

```python
    extension_manager = ExtensionManager(extensions)

    with extension_manager.request(context_value):
        ...
```

Will become:

```python
    extension_manager = ExtensionManager(extensions, context_value)

    with extension_manager.request():
        ...
```

Opinions?

**Comment by patrys** [comment]
Why not introduce `resolver_error` that takes a single error instance, the root value and the info object?

**Comment by rafalp** [comment]
I'm not convinced. This hook would have to live inside the `resolve` hook, and extension authors would have to remember about this gotcha. On flip-side if you want to somehow handle resolver errors, you can easily implement custom logic using existing `resolve` hook.

`has_errors` had added benefit of receiving all errors - it can take and report invalid queries and other such things, but I would like to expose context to this hook in a manner consistent with rest of hooks.
