### ISSUE TITLE
Upgrade to GraphQL-core v3

### ISSUE THREAD

**Issue by tlil** [mirumee/ariadne#244]
I'm getting the following deprecation warning. Is this something that is already on your radar / that you are planning to resolve for the next release?

>**DeprecationWarning**: GraphQL-core-next has been discontinued. It is now released as GraphQL-core v3 and newer.

**Comment by rafalp** [comment]
Thanks for raising this up.

We are aware that "GraphQL-core-next" v3 will be released as "GraphQL-core" v3, but there's currently no stable "GraphQL-core v3" release that we could update Ariadne to, with most recent release being [Alpha 2](https://pypi.org/project/graphql-core/#history).

On the flip-side of things, there are no known show-stopper issues in the version of GraphQL Core Next that we are using, sans this warning ;)

**Comment by tlil** [comment]
Yep, I saw. But thanks for clarifying regardless. :)

Just wanted to see whether it was on your radar and tracked somehow. It sounds like you got it covered :+1:

**Comment by rafalp** [comment]
Core 3 is now out, so we can release new Ariadne version with GraphQL-core-3!

Marking this as help wanted cos I'm not sure when I'll find time to sit down and do deps bump for Ariadne 0.9 release. If somebody cooks up the PR that does this, they are welcome!
