### ISSUE TITLE
Is Python `multipart` module used anywhere?

### ISSUE THREAD

**Issue by caladd** [mirumee/ariadne#253]
I can't find it being imported anywhere in the code. I'm trying to get my Ariadne environment slimmed down as much as possible, so it would be useful to know if it is safe to remove that module. Thanks!

**Comment by rafalp** [comment]
Its dependency for file uploads in ASGI server.

**Comment by tkamenoko** [comment]
@rafalp Are there any plans to move `multipart` to extras_require? Dropping unused dependencies looks reasonable when we don't use file uploads feature of `ariadne` .

**Comment by rafalp** [comment]
I guess we can make this optional for folk who need to keep their deps installation size cut to size.

Will need to add notes to our docs too.

**Comment by rafalp** [comment]
I'll move this behind `asgi-uploads` feature flag in Ariadne 0.8
