### ISSUE TITLE
'list' object has no attribute 'middlewares'

### ISSUE THREAD

**Issue by levrik** [mirumee/ariadne#256]
The following code raises the above error.

```python
def auth_middleware(resolver, obj, info, **kwargs):
    value = resolver(obj, info, **kwargs)
    return value

@graphql_api.route('/graphql', methods=["POST"])
def graphql_server():
    success, result = graphql_sync(
        schema,
        request.json,
        middleware=[auth_middleware]
    )
```

I think this is causing the issue: https://github.com/mirumee/ariadne/blob/2d2184939bf469f3a607bf3e08f2f27ca0fa7421/ariadne/extensions.py#L29-L30

Looks like the documentation isn't up to date or wrong since this is expecting an `MiddlewareManager` but the documentation shows a plain list. Or am I getting something wrong here?

**Comment by rafalp** [comment]
Yeah, docs are lying here 😅

I am thinking that we should update `ariadne.graphql` and `ariadne.graphql_sync` to accept list of middlewares instead of `MiddlewareManager` for simplicity's sake unless there are any advantages from providing `MiddlewareManager`?

**Comment by levrik** [comment]
Could you provide me some example of how to use the `middleware` argument on `graphql_sync` at the moment or point me to somewhere where I can find out more about it? I can't wait for a decision being made here.

**Comment by rafalp** [comment]
Ah, I see now where's the inconsistency.

`middleware=` argument on `graphql_sync` is supposed to be `MiddlewareManager([middleware_func1, middleware_func2, ...])` and not just list of middlewares.

**Comment by levrik** [comment]
Okay. Looks quite straightforward. Thanks!

**Comment by levrik** [comment]
Mhhh. So now I'm passing in `MiddlewareManager([auth_middleware])` to `graphql_sync` but the middleware never gets called.

**Comment by rafalp** [comment]
Correct, line I've linked to actually does `MiddlewareManager(*middlewares)` ;)

**Comment by levrik** [comment]
Yep. I'm quite new to Python so I didn't notice immediately 😅

**Comment by khasbilegt** [comment]
I created a [PR](https://github.com/mirumee/ariadne-website/pull/84) reflecting how it should be used at the moment.

**Comment by johnnyleitrim** [comment]
I see the PR that @khasbilegt , but that did not work for me either (using `0.15.1`). The only way I could get it to work is with the following code:

```python
def lowercase(resolver, obj, info, **args):
    print(f"lowercase: {obj}")
    value = resolver(obj, info, **args)
    if isinstance(value, str):
        return value.lower()
    return value


def lowercase_middleware(request: Any, context: Optional[ContextValue]):
    return lowercase,


app = GraphQL(schema, middleware=lowercase_middleware)
```

The `MiddlewareManager(*middlewares)` in the ariadne code means I needed to return a tuple of my middleware methods, even though there's only one.
