### ISSUE TITLE
Error handler hook

### ISSUE THREAD

**Issue by Rydez** [mirumee/ariadne#257]
Hey guys,

I'm trying to find a way to hook into Ariadne to get server errors, so that I can email stack traces to developers. It seems like I could do this with the `error_formatter`, but I don't want to override the default `error_formatter`. Is there a more direct way I could create an error handler?

Thank you!

**Comment by rafalp** [comment]
Ariadne logs errors to specified logger (defaults to [`ariadne`](https://github.com/mirumee/ariadne/blob/cbd9a2fd99791e3e4bdae80b3073b158b164cdd2/ariadne/logger.py#L13)) so you can define custom logger and send errors from it.

**Comment by Rydez** [comment]
Wow, that was fast!

Thank you very much!
