### ISSUE TITLE
Incorrect field ordering

### ISSUE THREAD

**Issue by sedough** [mirumee/ariadne#259]
According to the "Field Ordering" paragraph in Section 3.6 of the spec:

> When querying an Object, the resulting mapping of fields are conceptually ordered in the same order in which they were encountered during query execution, excluding fragments for which the type does not apply and fields or fragments that are skipped via @skip or @include directives. This ordering is correctly produced when using the CollectFields() algorithm.
>
>Response serialization formats capable of representing ordered maps should maintain this ordering. Serialization formats which can only represent unordered maps (such as JSON) should retain this order textually. That is, if two fields {foo, bar} were queried in that order, the resulting JSON serialization should contain {"foo": "...", "bar": "..."} in the same order.

Ariadne (using the graph_sync at least) returns JSON fields in alphabetical order.

**Comment by rafalp** [comment]
@sedough thanks for the report. `ariadne.graphql_sync` is a thin wrapper for `graphql.graphql_sync` implemented by [GraphQL-core-next](https://github.com/graphql-python/graphql-core-next).

Can you please confirm that same behavior happens during "raw" GraphQL query execution in it?

**Comment by sedough** [comment]
This ended up being an issue with Flask's jsonify() method:
https://github.com/pallets/flask/issues/974

Sorry!
