### ISSUE TITLE
Change load_schema_from_path arg to be a glob pattern

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#261]
Currently `load_schema_from_path` supports both path to `graphql` file and path to directory that is then recursively searched for `*.graphql`. We could instead change its argument to be glob pattern, eg:

```
schema = load_schema_from_path("/somewhere/schema/*.graphql")
# and if there are subdirectories we want to also support
schema = load_schema_from_path("/somewhere/schema/**/*.graphql")
```

**Comment by salwator** [comment]
Maybe we could keep both? Personally I would prefer to just put a path and don't bother with defining pattern, in most cases you would like to just keep schema in one directory tree with no other random .graphql files. You could easily use the main project source directory and get away with it having schema spread across modules.

**Comment by rafalp** [comment]
Fixed on master.
