### ISSUE TITLE
"Requested setting TEMPLATES, but settings are not configured. 

### ISSUE THREAD

**Issue by garimagupta715** [mirumee/ariadne#265]
Hi,

I am wrapping my existing apis by ariadne graphql . but when i am using Get api of ariadne/contrib/django/views.py to call existing rest end point,  getting below error even i have all configuration in setting.py file.

"message": "Requested setting TEMPLATES, but settings are not configured. 
You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.", 

Can you please help whats wrong here ,why it is not picking upsetting.py fie configuration

**Comment by rafalp** [comment]
Hello!

We are using Github issues tracker for tracking bugs and discussing library's code. To discuss general usage and problems, please ask on [Spectrum chat](https://spectrum.chat/ariadne).

Thank you!
