### ISSUE TITLE
Move from Travis to GitHub actions

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#268]

**Comment by justinmoon** [comment]
I just set up GitHub Actions on the project I'm using Ariadne in. Loved it so far. If I can find some freetime I'll try to implement this.

**Comment by rafalp** [comment]
@justinmoon thank you for for offering help, but you have to trust me when I'll say that it won't be that easy in this case. ;) We have workflow files ready and lying around that we could just add to the repo, but we've ran into an edge case about GH actions availability for org repos.

We are looking into ways to fix that, but until then we are staying with Travis, but thanks for offering help anyway!

**Comment by rafalp** [comment]
Original issue preventing this is no longer the case. Marking this as roadmap and help wanted.
