### ISSUE TITLE
Django subscriptions

### ISSUE THREAD

**Issue by globophobe** [mirumee/ariadne#283]
First, thanks for the great project.

I want to use subscriptions in Django. From the docs:

> If you wish to use subscriptions with Django, consider wrapping your Django application in a Django Channels container and using Ariadne as an ASGI server.

Correct me if I'm wrong, it sounds like I can't use the Django ORM.

Now, I don't really know what I'm doing, but I subclassed Channels `AsyncJsonWebSocketConsumer`, with the essential methods of `ariadne.asgi.GraphQL`. 

On connect and disconnect, the channel is added to group `graphql-ws`. 

Within start_websocket_subscription method of consumer:

```
async def start_websocket_subscription(data, operation_id, subscriptions):
    ...
    subscription_source = await self.channel_layer.new_channel()
    context_value['subscription_source'] = subscription_source
    self.subscription_sources.append(subscription_source)
    ...
```

Then, a message is broadcast from Django post_save signal:

```
def post_save_example(sender, **kwargs):
    channel_layer = get_channel_layer()
    obj = kwargs['instance']
    msg = {"type": "forward.subscription", "id": obj.id}
    async_to_sync(channel_layer.group_send("graphql-ws", msg)
```

Which is received by the channel's dispatch function:

```
async def forward_subscription(self, message):
    for subscription_source in self.subscription_sources:
        await self.channel_layer.send(subscription_source, message)
```

Which is handled by Ariadne:

```
@subscription.source("example")
async def example_generator(message, info):
    channel_layer = get_channel_layer()
    subscription_source = info.context['subscription_source']
    while True:
        msg = await channel_layer.receive(subscription_source)
        yield msg
```

It seems to be working, but I wonder if there is a better way. Your comments are appreciated.

**Comment by rafalp** [comment]
My experience with Django channels is super-limited, but I will answer this:

> Correct me if I'm wrong, it sounds like I can't use the Django ORM.

You can't do synchronous IO inside the event loop. Well, you can, but when you do, this blocks event loop until IO completes, which will kill performance in the multiple-users environment. Make sure you extract IO operations to functions decorated with `sync_to_async` when using synchronous IO like Django's ORM.

**Comment by globophobe** [comment]
Worded that wrong. 

> it sounds like I can't use the Django ORM.

Should have been. 

> it sounds like I can't update clients with data from subscriptions using Django ORM signals.

I think Ariadne pub/sub https://github.com/mirumee/ariadne/issues/165 will partially solve this, but there still needs to be a way to update clients with data from subscriptions such as when a user saves data using the Django admin.

My idea works, but creates a new channel for every subscription operation. 

So, a client with 10 subscriptions would result in 11 channels, 1 for the websocket connection, plus 1 for every subscription operation.
