### ISSUE TITLE
Custom lifespan handlers

### ISSUE THREAD

**Issue by jimtheplant** [mirumee/ariadne#286]
Hi,

I was wondering if there was any plan to implement the [lifespan](https://github.com/django/asgiref/blob/master/specs/lifespan.rst) protocol for the provided asgi server. I think this could be done with extensions or a passing new keyword args to the asgi object. Could be nice for things such as closing DB connections, startup error handling, ect.

**Comment by rafalp** [comment]
Hey!

Idea behind default server is to provide people with quick way to get their GraphQL server up and running locally so they can play around - write some schema, run some queries against it to see how resolvers are called, etc. etc.

Obviously this approach is unfit for great majority of "real apps" that will want to do things like manage DB connections and other things you've mentioned. But we really don't want to end up maintaining both the GraphQL server and the ASGI/HTTP stack.

If you need the entire thing, the recommended approach is to use the full-fledged ASGI server and `mount` Ariadne's ASGI application within it. Here's example how to do it with [Starlette](https://starlette.io): https://ariadnegraphql.org/docs/starlette-integration
