### ISSUE TITLE
Request Data and Cookies using ASGI Django Channels

### ISSUE THREAD

**Issue by ymoondhra** [mirumee/ariadne#292]
I have a front-end React Apollo application that requests data from the Django ASGI back-end.
I created my ASGI application with Django Channels using the guidelines found [here](https://ariadnegraphql.org/docs/django-integration.html#django-channels).

From the field resolver methods, there is no way to access cookies sent from the front-end to the back-end that is not part of the graphQL query. I need these cookies to check the session/authentication state of the request. Django has its own request object, which I usually access to check auth state. Somewhere along the way to the resolver function, this Django request object is lost. The most similar thing to this request object is `info.context['request']`, but this Starlette object does not have any relevant data.

I have researched this topic for roughly 8-10 hours.

**Here is some of my code.**
settings.py
`ASGI_APPLICATION = 'need.routing.application'`
schema.py
```
...

@query.field('cart')
def resolve_cart(_, info, id):
    request = info.context['request']
    print(request.cookies)
```
routing.py
```
class DjangoChannelsGraphQL(GraphQL): # source: https://github.com/mirumee/ariadne/issues/210
    def __call__(self, scope) -> None:
      async def handle(receive, send):
          await super(DjangoChannelsGraphQL, self).__call__(scope, receive, send)
      return handle

application = URLRouter([
    path("graphql/", DjangoChannelsGraphQL(schema, debug=True)),
    re_path(r"", AsgiHandler),
])
...
```

**Comment by rafalp** [comment]
Hello!

Can you please post your question on our [Spectrum](https://spectrum.chat/ariadne?tab=posts)? We are trying to keep GitHub issues focussed on bugs and development in Ariadne itself.

Thank you!

**Comment by 0dminnimda** [comment]
Any update on this? @ymoondhra how did you solved this?
