### ISSUE TITLE
Error importing module (circular import) when the local script is called graphql.py

### ISSUE THREAD

**Issue by v1b1** [mirumee/ariadne#294]
**Description**: when trying to import the ariadne module (either as `import ariadne` or `from ariadne import ...` when your own module file is named `graphql.py`, it causes the following error:

```
Exception has occurred: ImportError
cannot import name 'gql' from partially initialized module 'ariadne' (most likely due to a circular import) (/usr/local/lib/python3.8/site-packages/ariadne/__init__.py)
  File "/workspaces/project/graphql.py", line 1, in <module>
    from ariadne import gql
  File "/workspaces/project/graphql.py", line 1, in <module>
    from ariadne import gql
```

**Workaround**: Renaming your file from `graphql.py` to anything else resolves this error.

**Comment by patrys** [comment]
Well, your local module conflicts with `graphql-core-next` which is also called `graphql`. There is little we can do here, it's how Python imports work.

**Comment by v1b1** [comment]
Inside my actual calling file, say `app.py`, I include the line `from project.graphql import ...`. I don't seem to have problems with other module names sharing a name with other imported dependences, e.g. `from project.requests import ...` when I also use `requests` and `starlette.requests` in the same file.

**Comment by v1b1** [comment]
You're right, on further investigation, it does appear that if the base file is named the same as a module it imports, then the same thing occurs. That's an interesting quirk.
