### ISSUE TITLE
middleware using an object method does not work

### ISSUE THREAD

**Issue by shaozi** [mirumee/ariadne#295]
If I have a class method as the middleware, it is not called

This does not work:

```python
class M:
  def __init__(self):
    pass
  def middleware(self, resolver, obj, info, **args):
    print('m is called')
    return resolver(obj, info, **args)

m = M()
app = GraphQL(schema, middleware=[m.middleware])
```

however, if I wrap the method in another function, it works:

```python
m = M()
def middleware(resolver, obj, info, **args):
  return m.middleware(obj, info, **args)
app = GraphQL(schema, middleware=[middleware])
```

**Comment by rafalp** [comment]
Hi!

Correct GraphQL middleware needs to be either an callable or an object with method named `resolve`. Your function is valid middleware, but your object is not.

Here is example of Ariadne extension that is also correct middleware:

https://github.com/mirumee/ariadne/blob/master/ariadne/contrib/tracing/apollotracing.py#L25

**Comment by shaozi** [comment]
Cool. This is nice. Can you add to the documentation?

**Comment by rafalp** [comment]
https://ariadnegraphql.org/docs/middleware

> GraphQL middleware are Python __functions__ and __callable objects__ that can be used to inject custom logic into query executor.
