### ISSUE TITLE
File upload example

### ISSUE THREAD

**Issue by shaozi** [mirumee/ariadne#296]
Is there an example on how to save the file object in the file upload mutation? Document is lacking

**Comment by rafalp** [comment]
Hello!

Can you please post your question on our [Spectrum](https://spectrum.chat/ariadne?tab=posts)? We are trying to keep GitHub issues focussed on bugs and development in Ariadne itself.

Thank you!

**Comment by shaozi** [comment]
Ok. I got it. The `file.file` is a `SpooledTemporaryFile` object. Just read from it and write it to another file. Please add some document to Ariadne.

**Comment by rafalp** [comment]
Did you see the [documentation on `Upload` scalar value](https://ariadnegraphql.org/docs/file-uploads#implementation-differences)?
