### ISSUE TITLE
Implement GraphQL modules

### ISSUE THREAD

**Issue by patrys** [mirumee/ariadne#306]
GraphQL Modules are a JavaScript tool that allows types and resolvers to be grouped together into functional blocks that depend on each other. Modules can be composed to build larger parts, ultimately leading to a module that represents the entire application.

Importing a single module is easier than importing a list of types, resolvers, and any dependant types or resolvers. Modules are also a straightforward way to implement a code-first declarative interface like that offered by Strawberry. We could also provide tooling to build modules from Graphene and Strawberry objects.

**Comment by rafalp** [comment]
I've had short brainstorming session with @patrys about this, and initial idea is to introduce new base class that's basically type definition + requirements + resolvers, something like this:

```python
class User(ObjectType):
    # Validated to contain exactly single type declaration
    __schema__ = gql(
        """
        type User {
            id: ID!
            name: String!
            email: String
            group: UserGroup!
            joinedAt: DateTime!
            lastVisit: DateTime
        }
        """
    )
    # Optional, allows mapping fields to resolver functions in python
    # if mapping is defined here but function is not declared on class, it will be autogenerated
    __resolvers__ = {
        "joinedAt": "joined_at",
        "lastVisit": "last_visit",
    }
    # Optional, list of other GraphQL types/objects this type requires
    __requires__ = [UserGroup]

    # Resolvers methods
    @staticmethod
    def email(obj, info) -> Optional[str]:
        if can_see_email(info.context, obj):
            return obj.email
        
        return None

    @staticmethod
    def last_visit(obj, info) -> Optional[datetime]:
        if can_see_activity(info.context, obj):
            return obj.last_visit
        
        return None
```

**Comment by rafalp** [comment]
I've created feature branch where I'm experimenting on this implementation: [new-object-api](https://github.com/mirumee/ariadne/blob/new-object-api/ariadne_future/)

My plan is to keep iterating on to get into somewhat working stage for queries, mutations and scalars. When that gets somewhat useable I would like to start including `ariadne_future` in our releases to let people play with it for small APIs

**Comment by rafalp** [comment]
I've moved modules implementation to [ariadne-graphql-modules](https://github.com/mirumee/ariadne-graphql-modules) library. There was already single release of that lib to PYPI, but it will be broken until Ariadne 0.15 is released.

**Comment by rafalp** [comment]
Closing this issue. Dev on GraphQL modules for Ariadne will continue in `graphql-modules` library linked above.
