### ISSUE TITLE
graphql-playground:  playground_options being ignored

### ISSUE THREAD

**Issue by stestagg** [mirumee/ariadne#318]
It seems that due to:
https://github.com/prisma-labs/graphql-playground/issues/1037

The playground_options values are being ignored.

This is affecting me because the ariadne default: '"request.credentials": "same-origin",' is not being set, causing authentication issues.

The best workaround I can find is to manually change this setting through the graphql-playground UI on a per-browser basis.

I'm not expecting any code changes in ariadne, this is more of a tracking issue in case other people have the same problem.

Note: Due to the way the playground is built/loaded, it doesn't seem realistically possible to patch/work around this programatically.  https://github.com/prisma-labs/graphql-playground/issues/1037#issuecomment-559224565 suggests changing the redux store directly, but accessing the redux store seems prohibitively difficult.

**Comment by thebenwaters** [comment]
Waiting on PR #315 

I've tested locally and it works great. I wrote a wrapper that does a "login" and sets the header on render

**Comment by markedwards** [comment]
Just to be clear, this is purely a bug in `graphql-playground-react`, right?  There is no action item on the Ariadne side?

I'm pinging graphql/graphql-playground#1037 to see if I can figure out how to make progress on this.

**Comment by johncarter-phntm** [comment]
I think we just have the wrong shape for the options dict? Nesting the existing config as a {"settings": value} seems to fix the issue?

eg

```{"settings": {"request.credentials": "same-origin"}}```

Works as expected for me. I don't know if this bug has always been there, or if graphql playground changed the options format at some point?

This bug exists on ariadne_django as well.

**Comment by johncarter-phntm** [comment]
Ah, already fixed by https://github.com/mirumee/ariadne/pull/642 / https://github.com/reset-button/ariadne_django/pull/41

I think this can be closed?
