### ISSUE TITLE
Really slow for huge list of objects

### ISSUE THREAD

**Issue by levrik** [mirumee/ariadne#319]
```graphql
type FooBar {
  # some more flat fields
}

type Bar {
  n: Int!
  sub: FooBar!
}

type Foo {
  foo: [Bar!]!
}
```

We have a structure like this. The `foo` property on `Foo` can contain thousands of items. Sadly we need all of them at once, so we can't paginate over it.
There's only one resolver to resolve `foo` itself which is quite fast (getting the nested object from a Mongo DB).
Our current workaround is to implement a custom `JSON` scalar which just returns the data, by-passing all child resolvers. But this way we're loosing everything that GraphQL gives us.
Is there anything that can be used to speed this up without using a `JSON` scalar or is this the best solution already? I know that GraphQL comes with some overhead but this can go up to 20 seconds vs 1 second with `JSON` scalar.

We're using Ariadne in sync-mode.

**Comment by rafalp** [comment]
Performance discussion for GraphQL Core Next: https://github.com/graphql-python/graphql-core-next/issues/54

I'm afraid there isn't much we can do in Ariadne to speed things up for cases such as these. Query executor does plenty of function calls to resolve values. There's functions all the way down, with at least 3 for each value returned for field: resolver call, `isawaitable` check, scalar `serialize` call for the returned value. This easily adds up if you have A LOT of data.

Low hanging fruit for Ariadne that comes to mind would be adding cache to query parser (parsing complex queries can make up to 20% of query execution time), but that's really only buying time before somebody else returns even more data from their query.

**Comment by levrik** [comment]
I just did some profiling and, indeed, the slowest part is everything that is happening inside `graphql-core-next`. Then probably the `JSON` scalar is the best fit here.

**Comment by Dodobibi** [comment]
I think than `graphql-core-next `must be written in C (cython) for drastically increase performances. My first tests confirm this.

I'm trying to rewrite it with cython but it's a huge work.
This is the only way to increase performances,  when recursives calls...

**Comment by patrys** [comment]
Out of curiosity, have you considered using PyPy? (Disclaimer: it only supports Python 3.6 for now, 3.7 support is underway.)

**Comment by Dodobibi** [comment]
> Out of curiosity, have you considered using PyPy? (Disclaimer: it only supports Python 3.6 for now, 3.7 support is underway.)

I can't (I need last version of hypercorn wich need python >= 3.7)

Have you tried with pypy ? What about the performances ?

**Comment by patrys** [comment]
I don't have any precise data about Ariadne to share but I've heard people mention that in their tests PyPy made pure-Python ASGI servers as fast as uvicorn or hypercorn.

**Comment by rafalp** [comment]
Looks like graphql-core 3.1 is promising performance improvements in query executor, but we'll have to update our codebase to support it.

**Comment by levrik** [comment]
@rafalp Looks like this could improve with the `0.13` of Ariadne?

**Comment by rafalp** [comment]
@levrik correct. We've updated GraphQL-Core to 3.1 in 0.13 and will ship it in few weeks, once the rest of features pull requests have been merged.

**Comment by rafalp** [comment]
For the record, here's the PR: #393

**Comment by cancan101** [comment]
@rafalp any updates on getting the 0.13 release of Ariadne published with the upgrading of graphql-core to 3.1 change?

**Comment by rafalp** [comment]
I want to release 0.13 soon with GraphQL core bumped to 3.1.3.

**Comment by rafalp** [comment]
Ariadne 0.13 has been released. Closing this.
