### ISSUE TITLE
Subscriptions "Complete Example" breaks under 0.10.0

### ISSUE THREAD

**Issue by command-tab** [mirumee/ariadne#320]
I'm working with Subscriptions in ariadne using the exact code from the [Complete Example](https://ariadnegraphql.org/docs/subscriptions#complete-example) in the docs. When I load the playground and issue the query `subscription { counter }`, instead of a working counter, an "unsupported operand" error is raised:

```
Traceback (most recent call last):",
  File \"/Users/...REDACTED.../virtualenvs/graphql-Pfr5HTvn/lib/python3.7/site-packages/graphql/execution/execute.py\", line 625, in resolve_field_value_or_error",
    result = resolve_fn(source, info, **args)",
  File \"/Users/...REDACTED.../app/__init__.py\", line 26, in counter_resolver",
    return count + 1",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'"
```

What's wild is that the example in the docs works with ariadne 0.8.0 and 0.9.0, but not 0.10.0. I'm not familiar enough with the internals, though, to spot the issue in the [0.9.0...0.10.0 diff](https://github.com/mirumee/ariadne/compare/0.9.0...0.10.0).

(For completeness, I'm using Python 3.7.6, ariadne 0.10.0, under uvicorn 0.11.2 and gunicorn 20.0.4.)

**Comment by rafalp** [comment]
Looks like #288 borked this. Workaround for the issue would be to specify operation's name:

```
subscription MySubscription {
    counter
}
```

**Comment by zero-shubham** [comment]
> Looks like #288 borked this. We'll have to implement more proper approach for finding if executed operation will be query or subscription.
> 
> In a meantime workaround for the issue would be to specify operation's name:
> 
> ```
> subscription MySubscription {
>     counter
> }
> ```

just curious why does this work?

**Comment by rafalp** [comment]
New logic introduced in #288 checks for operation name. `subscription {}` has no operation name, but `subscription Something {}` does.

**Comment by shaozi** [comment]
0.12.0 still has this issue?


```Graphql
subscription MySubscription {counter}
```

```json
{
  "error": "Could not connect to websocket endpoint ws://localhost:8000/. Please check if the endpoint url is correct."
}
```

Using the example in the document

**Comment by shaozi** [comment]
my bad. I am using `uvicorn`, turns out I also need to `pip install websockets` for the server to support web sockets

**Comment by leminhson2398** [comment]
> my bad. I am using `uvicorn`, turns out I also need to `pip install websockets` for the server to support web sockets

@shaozi , does it work for you ?

**Comment by leminhson2398** [comment]
> my bad. I am using `uvicorn`, turns out I also need to `pip install websockets` for the server to support web sockets

@shaozi, actually that does not make sense, i implemented the following way instead and it works:

```python3
from ariadne import QueryType, SubscriptionType, make_executable_schema
from ariadne.asgi import GraphQL
from starlette.applications import Starlette
import asyncio
import uvicorn
from starlette.routing import Route, WebSocketRoute


type_defs = """
    type Query {
        hello: String!
    }

    type Subscription {
        counter: Int!
    }
"""

subscription = SubscriptionType()


@subscription.source("counter")
async def counter_generator(obj, info):
    for i in range(5):
        await asyncio.sleep(5)
        yield i


@subscription.field("counter")
def counter_resolver(count, info):
    return count + 1


query = QueryType()


@query.field("hello")
async def resolve_hello(*_):
    return "Hello World"


schema = make_executable_schema(type_defs, query, subscription)


routers = [
    Route("/graphql", GraphQL(schema=schema, debug=True)),
    WebSocketRoute("/graphql", GraphQL(schema=schema, debug=True)),
]

app = Starlette(debug=True, routes=routers)


# if __name__ == "__main__":
#     uvicorn.run("main:app", host="127.0.0.1", port=5000, log_level="info")

```

**Comment by ChronoDK** [comment]
I have the example running, but how do I test it in the playground? What is the query I must make?
