### ISSUE TITLE
[Question] How does the default resolver lookup work?

### ISSUE THREAD

**Issue by frthjf** [mirumee/ariadne#327]
Hi, 

I have written some classes that provide the resolvers for the schema defined in `*.graphql` files. I guess I can bind them all manually using ``query = ObjectType("Query")`` etc. but that seems quite cumbersome. Instead, it seems like I could just rely on the [default resolver](https://ariadnegraphql.org/docs/resolvers#default-resolver) to bind the objects automatically following some naming convention. However, it is not clear to me where these objects (e.g. ``class UserObj`` or ``user_dict``) have to be placed so that the default resolver finds them. In the GraphQL PHP server Lighthouse, you need to place the classes under a namespace and I guess in Python it would be some module path; can somebody explain what objects are being considered by the default resolver?

Many thanks!

**Comment by rafalp** [comment]
Hello @frthjf!

Thank you for asking - I'll be happy to explain, but we are using Github Issues for tracking bugs and todos, and ask all to use our [Spectrum](https://spectrum.chat/ariadne) for asking general questions about usage, practices and implementation details.

Thank you!

**Comment by frthjf** [comment]
Hi @rafalp. Sorry about that, I've cross-posted the question on [Spectrum](https://spectrum.chat/ariadne/general/how-does-the-default-resolver-lookup-work~09b9a510-f9fd-4aeb-ad7b-35427a277b65). Thanks.
