### ISSUE TITLE
Any plans to implement Apollo Gateway?

### ISSUE THREAD

**Issue by command-tab** [mirumee/ariadne#332]
Looking at the [Federated Gateway docs](https://ariadnegraphql.org/docs/apollo-federation#federated-gateway), I see the example uses Apollo Gateway to federate related Ariadne GraphQL services. Are there any plans to replicate Apollo Gateway such that a complete federated graph can be run on _only_ Python, rather than mostly Python and some Javascript? Thanks!

**Comment by rafalp** [comment]
Hi, thanks for asking!

We've done a quick look on implementing federation composition capabilities but decided against it (for now). It would take considerable amount of time that we could've placed elsewhere + there's usually no problem in proxying your Ariadne services behind Apollo-Server in production environments.

**Comment by Ambro17** [comment]
+1 To implementing the first intelligent gateway in python. I'm open to contribute
