### ISSUE TITLE
Custom errors raised by resolvers are not formatted

### ISSUE THREAD

**Issue by ex-nerd** [mirumee/ariadne#339]
I'm attempting to mimic a couple of the errors in apollo-server, and want to include a `code` value in the extensions, as such:

```python
class AuthenticationError(Exception):
    @property
    def formatted(self) -> dict:
        return {"message": self.message, "extensions": {"code": "UNAUTHENTICATED",}}

def throwError(_, info: ResolveInfo):
    raise AuthenticationError("dummy auth error")
```

After much stack debugging, I discovered that python's `graphql.error.located_error.located_error()` is wrapping my custom child class in a new instance of `GraphQLError`, so its `formatted` property is never accessed by ariadne.

According to the [ariadne error-messaging documentation](https://ariadnegraphql.org/docs/error-messaging), the default formatter "Unwraps GraphQL error by accessing its original_error property". And while I realize that in [the code](https://github.com/mirumee/ariadne/blob/master/ariadne/format_error.py#L12) this is happening exactly in the order described in the docs, this also means that the `formatted = error.formatted` is being called on the result of `located_error()` rather than the original one that was thrown.

Additionally, when I hook the debugger into `format_error`, it shows that my original error is actually double-wrapped, and only accessible by drilling two layers deep via `error.original_error.original_error` (the first level `error.original_error` is another GraphQLError ... not quite sure where the double-wrapping got added)

It *feels* like there is a bug in here somewhere (especially with that nested original_error), but it's certainly the case where the documentation could use some work explaining what actually happens under the hood, since as written, it sounds like it should be possible to just add a `formatted` property on an error and expect it to be reported to the API (which is definitely not the case).

**Comment by rafalp** [comment]
This is working as intended I am afraid - its part of spec that exceptions encountered during query execution are wrapped in `GraphQLError`.

Have you tried extending `GraphQLError` instead?

```
class AuthenticationError(GraphQLError):
    extensions = {"code": "UNAUTHENTICATED"}
```

This will result in `code` appearing in `extensions` value of GraphQL result.

**Comment by ex-nerd** [comment]
@rafalp Even if it's "working as expected", the ariadne documentation could use some help in clarifying that. Simply stating that everything gets wrapped in (potentially multiple) `GraphQLError`s would go a long way to reducing confusion how to handle propagating data from custom error types back to the client.

**Comment by rafalp** [comment]
This is a valid feedback - we are keeping a close eye to what gets raised up on our issue tracker and spectrum, and are updating our docs accordingly.

I would also like to add that exceptions raised from resolvers getting wrapped in `GraphQLError` which is then wrapped by other `GraphQLError` is just one of few gotchas to keep on mind when implementing custom `error_formatter`. For example `original_error.original_error` can be `None` if exception raised extended `GraphQLError`.  `original_error` can also be `None` if `GraphQLError` was raised during query validation.

**Comment by ex-nerd** [comment]
Just adding for posterity ... setting extensions to a class variable when the parent class expects them to be an instance variable is bad form (and doesn't actually seem work since `GraphQLError.__init__()`  overwrites `self.extensions` with the value passed into it, which defaults to None).

This does work, though:

```python
class AuthenticationError(GraphQLError):
    def __init__(self, message: str) -> None:
            super().__init__(message, extensions={"code": "UNAUTHENTICATED"})
```

**Comment by rafalp** [comment]
I've tried reproducing Apollo's errors approach in past and I don't remember it ever being nearly as troublesome as you are describing it.

Turns out you aren't supposed to extend `GraphQLError` in your exception, extending regular `Exception` does the trick just fine:

```python
from ariadne import QueryType, make_executable_schema
from ariadne.asgi import GraphQL


class AuthenticationError(Exception):
    extensions = {"code": "UNAUTHENTICATED"}


type_def = """
    type Query {
        field: Boolean
    }
"""

query_type = QueryType()


@query_type.field("field")
def counter_resolver(*_):
    raise AuthenticationError("PLEASE LOGIN")


schema = make_executable_schema(type_def, query_type)
app = GraphQL(schema, debug=True)
```

GraphQL response:

```json
{
  "data": {
    "field": null
  },
  "errors": [
    {
      "message": "PLEASE LOGIN",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "field"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED",
        "exception": {
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/Users/rafalpiton/github/ariadne/venv/lib/python3.7/site-packages/graphql/execution/execute.py\", line 625, in resolve_field_value_or_error",
            "    result = resolve_fn(source, info, **args)",
            "  File \"./errortest.py\", line 21, in counter_resolver",
            "    raise AuthenticationError(\"PLEASE LOGIN\")",
            "errortest.AuthenticationError: PLEASE LOGIN"
          ],
          "context": {
            "_": "(None, GraphQLResolv...0x105cee080>}))"
          }
        }
      }
    }
  ]
}
```

And same query with `DEBUG=False`:

```
{
  "data": {
    "field": null
  },
  "errors": [
    {
      "message": "PLEASE LOGIN",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "field"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED"
      }
    }
  ]
}
```

You also don't need to write any custom formatting logic for this because when query executor wraps exception in `GraphQLError`, it does `graphql_error.extensions = original_error.extensions`, effectively passing error code data up to error formatter.

**Comment by ex-nerd** [comment]
I found the final piece of my problem..  I'm raising errors from inside of a `context_value` function ... but any exceptions thrown from there never actually make it to ariadne's formatter (whether they are `GraphQLError`s or not).

**Comment by rafalp** [comment]
Yeah, we don't support that because `context_value` is executed in `ASGI`/`WSGI` app which is outside of our error handling logic, itself packed in `graphql()` and `graphql_sync` functions.

Still, thats curious case. Are you trying to make decision if user has access to GraphQL API at the time of creating `context_value`?

**Comment by ex-nerd** [comment]
Yeah.  Using the context phase to initialize the user context/session (via `Authorization` header).  It seemed like the appropriate place to ensure that everything was available and bail out early for invalid tokens before even trying to resolve the request.

**Comment by nilansaha** [comment]
Not sure if its related but any exceptions throw from inside the resolver does not surface up. It's logged in Ariadne logger but thats it. Any idea how I can surface the exceptions ?

**Comment by rafalp** [comment]
@nilansaha its not related but part of GraphQL spec to eat up exceptions raised from resolvers and return them as part of `errors` key in GraphQL result.

**Comment by nilansaha** [comment]
I see. Thanks for the info. Is there any way around that ? I want to log the exceptions from inside the resolver to Sentry

**Comment by rafalp** [comment]
@nilansaha this is not related to this issue. Please ask question on discussions instead.
