### ISSUE TITLE
Support Apollo subscriptions-transport-ws client

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#341]
Apollo [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) package adds client and server support for running GraphQL queries and mutations over web socket.

In #288 support for the client package has been introduced to the Ariadne, but the change broke GraphQL subscriptions for clients

In order to support this feature properly we would have check not only for operation name, but also for its presence in parsed query document, and its operation type in same document. Simplest fix would be to run parse() within `ariadne.asgi.GraphQL`, handling its errors there and then carrying on as described.

**Comment by fdemian** [comment]
Hi, I'm using Apollo Client on my frontend, and just came across this issue. I'd like to help but don't know where to start. What is needed to get graphql subscriptions to work with ariadne? 

Cheers!

**Comment by rafalp** [comment]
@fdemian this should be supported in Ariadne 0.16, thanks to @pigletto contributing support for multiple WS protocol handlers.
