### ISSUE TITLE
example of how to use query filter and limit 

### ISSUE THREAD

**Issue by 7seven7lst** [mirumee/ariadne#343]
Not sure how to implement complex query filtering and limit
I have the following simple example for query Movie of year 1920
```
{
  Movie(year: 1920) {
    title
  }
}
```

However, What if I want to query for movie that is less than, less or equal, greater than, greater or equal?

is there any way I can do it without specifying a long list of options like:
```
{
  Movie(year_lt: 1920, year_gte:1910) {
    title
  }
}
```

If so how would I implement the Movie type and query type?

**Comment by rafalp** [comment]
Thank you for your interest in Ariadne!

We are using GitHub issues exclusively for tracking bugs, problems, and roadmap for Ariadne codebase.

For usage examples and how-to, please ask on [Spectrum](https://spectrum.chat/ariadne) instead.

Thank you for your understanding.
