### ISSUE TITLE
Ariadne is not compatible with graphql-core 3.1

### ISSUE THREAD

**Issue by amoriello** [mirumee/ariadne#345]
Hi folks,

I'm hitting this error with the very example at https://www.starlette.io/

```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route


async def homepage(request):
    return JSONResponse({'hello': 'world'})


app = Starlette(debug=True, routes=[
    Route('/', homepage),
])
```

```
  File "./example.py", line 1, in <module>
    from ariadne import QueryType, make_executable_schema
  File "x/lib/python3.8/site-packages/ariadne/__init__.py", line 11, in <module>
    from .graphql import graphql, graphql_sync, subscribe
  File "x/lib/python3.8/site-packages/ariadne/graphql.py", line 18, in <module>
    from graphql.validation.rules import RuleType
```

```
❯ python --version
Python 3.8.2

❯ pip freeze | grep "ariadne"
ariadne==0.10.0

❯ python -c "import graphql; print(graphql.__version__)"
3.1.0b2
```

Digging a bit:

Looks like this [commit](https://github.com/graphql-python/graphql-core/commit/2744051ec8be7dd1d2eae6d08947106f6c12e86a#diff-4c0d14e6bf0dcc681bb5ad2994e432e3L13) from `graphql-python` removed `RuleType` from `graphql.validation.rules`

Thanks!

**Comment by rafalp** [comment]
Thanks for reporting.

Seems that meantime solution is to manually add `graphql-core<3.1` to your dependencies.

**Comment by rafalp** [comment]
GraphQL Core 3.1 has been released, so this task can land as part of Ariadne 0.12

**Comment by rafalp** [comment]
Delaying this to Ariadne 0.13. I would like to finally release Ariadne 0.12, and I won't be able to do it without delaying some of work for later.

Sorry everyone!

**Comment by nikordaris** [comment]
@rafalp I think I got graphql-core 3.1 working. See #393

**Comment by sarendsen** [comment]
Pull requests works for me. Around 25% speedup.

**Comment by nikordaris** [comment]
@rafalp would it be possible to get a RC pre-release published for this fix? The current performance hit is a pretty big deal to my company right now and we'd prefer to not fork an internal release with this fix.

**Comment by rafalp** [comment]
@nikordaris I don't think so. Can't you create custom branch on your repo and update your project's deps to use git URL in the meantime?
