### ISSUE TITLE
SchemaDirectiveVisitor does not visit field definitions on Subscription types

### ISSUE THREAD

**Issue by seanaye** [mirumee/ariadne#352]
I have a SchemaDirectiveVisitor that I'm using to authenticate certain sections of my API

```gql
directive @auth(
    roles: [Role]! = [USER]
    actions: [Action]! = []
) on FIELD_DEFINITION

type Query {
    me: UserResponse! @auth
    ...
}

type Subscription {
    invoice: PaidInvoiceResponse! @auth
}
```
The directive injects the authenticated user into the root value of these queries

```python
class AuthDirective(SchemaDirectiveVisitor, LoggerMixin):

    def visit_field_definition(self, field, *_):
        orig_resolver = field.resolve or default_field_resolver

        # define wrapper
        async def check_auth(obj, info, **kwargs):
            self.logger.critical('entering wrapper')
            # do some checks and return user or error
```

This works exactly as expected for normal queries/mutations but the class does not visit subscription types.

For every non-subscription field that I query, it logs `entering wrapper`

However when I try to subscribe that doesnt happen and the root obj of subscription source is None

Is the directive visiting the field resolver and not the generator? Is there a way to inject into the generator instead of the resolver.

To me it makes sense to visit the generator as this is where the bulk of the logic is and it is 'upstream' of the field resolver

**Comment by rafalp** [comment]
Can you please confirm that `visit_field_definition` (and not `check_auth`) is called for the `invoice` field on schema creation?

If it's not, then its a bug in Ariadne, but if it does, then you'll need to update your visitor to handle subscription fields accordingly (changing their `source` and not `resolve` attributes).

**Comment by seanaye** [comment]
@rafalp Thank you for quick reply. check_auth is called for invoice subscription, which must mean it visits the field and not the generator source. Could you please provide a short snippet of how I would handle changing `source` attribute

**Comment by seanaye** [comment]
Nevermind i see it. Thanks for your help
