### ISSUE TITLE
Exception in default_literal_parser() when ValueNode has no "value" member

### ISSUE THREAD

**Issue by markedwards** [mirumee/ariadne#356]
The [default_literal_parser() function](https://github.com/mirumee/ariadne/blob/master/ariadne/scalars.py#L90) in ariadne.scalars expects nodes to have a "value" member.  However, this is not the case with, for example, `ObjectValueNode` or `ListValueNode`.  This causes an exception when trying to pass such nodes.

My suggestion is to use `graphql.utilities.value_from_ast_untyped` instead:
```
return value_parser(value_from_ast_untyped(ast))
``` 

I'm happy to do a PR if you guys like this change.

**Comment by rafalp** [comment]
Yup, this sounds like a good improvement!

**Comment by markedwards** [comment]
#357
