### ISSUE TITLE
Argument 'code' has invalid value "ABC"

### ISSUE THREAD

**Issue by jonahmolinski** [mirumee/ariadne#371]
I think there is a bug when using both literal and variable values with a custom scalar.

```python
from ariadne import ScalarType

testscalar = ScalarType('TestScalar')

@testscalar.serializer
def serializer(value):
    return value.upper()


@testscalar.value_parser
def value_parser(value):
    if value:
        return serializer(value)


@testscalar.literal_parser
def literal_parser(ast):
    value = str(ast.value)
    return value_parser(value)
```

If you then make the following query:
```graphql
query($code: TestScalar) {
  test1: testType(code: $code) {
    id
  }
  test2: testType(code: "ABC") {
    id
  }
}
```
 This error is returned: Argument 'code' has invalid value "ABC"

If you don't pass variables and only use "literal" values it works. Same for if you only pass variables it works fine.

If you don't set up a resolver for "testType" then no error is returned.

Not sure what is happening but I think this is a bug. If not, does anyone know why this is happening?

**Comment by thebenwaters** [comment]
Can you post the SDL for testType?

**Comment by JonahMolinski** [comment]
Sure thing! Here is the entire SDL

```graphql
type Query {
  testType(code: TestScalar): TestType
}

scalar TestScalar

type TestType {
  id: ID!
  code: TestScalar
}
```

**Comment by rafalp** [comment]
Seems that there's already an PR with fix for it: https://github.com/mirumee/ariadne/pull/280

**Comment by rafalp** [comment]
According to explanation I've received, reference implementation calls `parse_literal` with second argument being query's variables dict when its present.
