### ISSUE TITLE
Context contains dictionary instead of request object

### ISSUE THREAD

**Issue by the-papi** [mirumee/ariadne#408]
Hello,
today I found that pull request #284 broke `info.context` that contains `{"request:" request}` instead of request object (as in version 0.11.0).

Are you going to fix it, or should I change my production code?

![image](https://user-images.githubusercontent.com/17556501/89785807-3ea7b680-db1b-11ea-9ab5-7cffbe8bd070.png)

**Comment by patrys** [comment]
While we did not catch that change, it does make the context consistent between different implementations of the server.

**Comment by PapiCZ** [comment]
Yep. I like that change. But it cost me about 3 hours of my time, so I think it should be at least mentioned in the changelog.

**Comment by patrys** [comment]
I agree, paging @rafalp

**Comment by PapiCZ** [comment]
I just want to make sure you won't change it back in the next version of ariadne.

**Comment by rafalp** [comment]
Hi @PapiCZ, thanks for bringing this up.

This change is here to stay, for consistency between server implementations (as well as our docs).

> I also don't think you should make these breaking changes between minor versions. There should be at least some kind of backward compatibility.

Please take note that Ariadne’s major is at „0”, which in our eyes signifies that things are still not set in stone. Hovewer of all changes we’ve introduced to the library over recent year or so, this is AFAIR only breaking change.

Thanks for bringing this up, and sorry for this suprise.

**Comment by andreasnuesslein** [comment]
just ran into the same thing. I think a note in the changelog here https://github.com/mirumee/ariadne/releases would be helpful ..
Thank you :)

**Comment by rafalp** [comment]
Closing this as we no longer provide Django app out of the box.
