### ISSUE TITLE
Unable to define multiple primary keys

### ISSUE THREAD

**Issue by bailey-byb** [mirumee/ariadne#414]
The Apollo Federation docs (and apollo-server), have a feature to [define multiple primary keys][1]. This allows different services resolve the entity by different fields. Here is the example from the Apollo docs:

```
type Product @key(fields: "upc") @key(fields: "sku") {
  upc: String!
  sku: String!
  price: String
}
```

Running this in ariadne (I am running `0.12.0`), gives me the error: (the code to replicate is below)

```
TypeError: The directive 'key' can only be used once at this location.
```

In my case, I am happy to steer clear of this feature, however, our other microservices (running on Node) take advantage of this and there may come a time we want to take advantage of these types.

_Code to replicate:_

```
# schema file
from ariadne.contrib.federation import make_federated_schema

type_defs = """
type Query
type Mutation

type Product @key(fields: "upc") @key(fields: "sku") {
  upc: String!
  sku: String!
  price: String
}
"""

schema = make_federated_schema(type_defs)

...

# Flask server

@app.route("/graphql", methods=["POST"])
def graphql_server():
    # GraphQL queries are always sent as POST
    data = request.get_json()

    # Note: Passing the request to the context is optional.
    # In Flask, the current request is always accessible as flask.request
    success, result = graphql_sync(
        schema,
        data,
        context_value=request,
        debug=app.debug
    )

    status_code = 200 if success else 400
    return jsonify(result), status_code
```

[1]:https://www.apollographql.com/docs/apollo-server/federation/entities/#defining-multiple-primary-keys

**Comment by delyanr** [comment]
The `graphql-js` specs, which is what `graphql-core` is based off, do not allow repeatable directives on OBJECT. You can see this clearly in the following [tests](https://github.com/APIs-guru/graphql-js/blob/736a8357e65853b797bb769ea322cf1956113d5f/src/validation/__tests__/UniqueDirectivesPerLocationRule-test.js).

I suggest you use the following instead:

```gql
type Product @key(fields: "upc sku") {
  upc: String!
  sku: String!
  price: String
}
```
