### ISSUE TITLE
Make snake_casing more consistent

### ISSUE THREAD

**Issue by kissgyorgy** [mirumee/ariadne#418]
Hi! Pretty neat project!

I have a "complaint" about snake_casing **consistency** throughout the whole framework.  
The `convert_camel_case_to_snake`, `convert_kwargs_to_snake_case` `snake_case_fallback_resolvers` are really helpful, but the picture is not complete, because there is no tool in the framework to convert incoming request data keys to snake_case. This is very problematic, because it means **integrating with other frameworks** like Django REST Framework serializers or Marshmallow will be a **lot of manual work**.  

Also I think the most common (even enforced most of the time with linters) casing in Python world is snake_case, but in JavaScript world, is camelCase. I think the perfect place to merge/convert the two worlds is the I/O boundary, in a web server/framework like ariadne and developers should know about the conversion, but should not write code about converting snake casing back and forth.

Here is _my suggestion_: Make converting the default from camelCase to snake_case in case of incoming requests, and make the snake_case_fallback_resolvers the default instead of opt in. Also apply the `convert_kwargs_to_snake_case` decorator to resolvers automatically.  
At this point in the project, it's still not too late to make a breaking change like this, because it's pre-1.0.

Here is what I did for the incoming requests:

```python
import ...

def recursive_snake_convert(data: Mapping):
    if isinstance(data, list):
        return [recursive_snake_convert(e) for e in data]
    elif isinstance(data, Mapping):
        return {convert_camel_case_to_snake(k): recursive_snake_convert(v) for k, v in data.items()}
    return data

def convert_request_kwargs_snake_case(resolver, obj, info, **kwargs):
    snake_keys_kwargs = recursive_snake_convert(kwargs)
    return resolver(obj, info, **snake_keys_kwargs)

type_defs = load_schema_from_path("schema.graphql")
schema = make_executable_schema(type_defs, [snake_case_fallback_resolvers, query, mutation])
app = GraphQL(schema, middleware=[convert_request_kwargs_snake_case])
```

This is just an example of how to do it, but the point is the general idea that case conversion should be consistent on every part of the framework.

I'm willing to work on this if we can agree on the topic beforehand.

**Comment by kissgyorgy** [comment]
Actually, the above method doesn't work, because internal resolver incoming data is also converted, which expect camelCase.  
A better solution would be if `convert_kwargs_to_snake_case` would recursively convert the kwargs keys.

**Comment by pvlplv** [comment]
It would be nice, if out coming dict keys could be converted from snake_case to camelCase back. I’m using sqlalchemy with Ariadne, and my resolvers return SA models. I could use pydantic aliases to convert attribute names, but I ended up just using snake_case everywhere.

**Comment by rafalp** [comment]
@kissgyorgy

**Comment by rafalp** [comment]
@kissgyorgy

> A better solution would be if `convert_kwargs_to_snake_case` would recursively convert the kwargs keys.

This is exactly what is supposed to happen: https://github.com/mirumee/ariadne/blob/master/ariadne/utils.py#L30

> I ended up just using snake_case everywhere.

You can put `snake_case_fallback_resolvers` in `make_executable_schema` to make default resolvers map from `camelCase` in your schema to `snake_case` in Python. Documentation is available [here](https://ariadnegraphql.org/docs/resolvers#fallback-resolvers).

**Comment by kissgyorgy** [comment]
That's the first resolver I have as bindables, so this is a bug report I guess?

**Comment by rafalp** [comment]
@kissgyorgy Sorry, it's not clear to me then. Could you provide an isolated example of what you are doing?

Thanks!

**Comment by pvlplv** [comment]
@rafalp 
> You can put `snake_case_fallback_resolvers` in `make_executable_schema` to make default resolvers map from `camelCase` in your schema to `snake_case` in Python. Documentation is available [here](https://ariadnegraphql.org/docs/resolvers#fallback-resolvers).

Thanks for the tip!
It worked!

**Comment by rafalp** [comment]
Marking this as bug for me to remember to check if `snake_case_fallback_resolvers` really doesn't work.

**Comment by kissgyorgy** [comment]
Sorry for the late reply. 
I checked the project I thought this is not working, and I removed my own decorator and `@convert_kwargs_to_snake_case` is working as expected. Sorry about the noise, feel free to close.

Although I still want to suggest my other point, that these should be defaults instead of opt-in and have just documented. The first thing I do for every project is use the `snake_case_fallback_resolvers` and use the `@convert_kwargs_to_snake_case`  decorators everywhere.

What do you think about that?
