### ISSUE TITLE
Graphql playground doesn't load in the browser with Django 3.1.1

### ISSUE THREAD

**Issue by gghildyal** [mirumee/ariadne#421]
I created a new project which uses Django 3.1.1 and followed the instructions to integrate with Django (with GraphQLView.as_view). When I visit http://localhost:8000/graphql/ all I see is a large graphql icon that fills the screen and text below saying 'Loading GraphQL playground'. Nothing happens after that and I have no errors on the server logs.

Note, installing the desktop app for Graphql playground and visiting the link works fine. It's only that the playground doesn't load up on the browser. Could it be some incompatibility with latest Django version?

**Comment by rafalp** [comment]
Did you check if there are any errors in browser's console?

**Comment by gghildyal** [comment]
That's silly of me, I should have checked that first. The console logs are complaining about Content Security Policy because style-sheets for the playground are fetched from an external source. 

I have CSP configured, so I will fix that first. Apologies for raising the issue - I will fix the CSP issues and close this off as soon as it works.

**Comment by gghildyal** [comment]
Works like a charm! For anybody else using CSP, this is the code you would need to wrap around the GraphQL view.

 

```
from csp.decorators import csp_exempt
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
  ...
  ...
  path(
        'graphql/',
        csrf_exempt(csp_exempt(GraphQLView.as_view(schema=schema))),
        name='graphql'
    ),
  ..
  ]
```
