### ISSUE TITLE
django goes async, will using ariadne without channels be possible?

### ISSUE THREAD

**Issue by janwout** [mirumee/ariadne#423]
django goes async, will using ariadne without channels be possible?

https://docs.djangoproject.com/en/3.1/topics/async/
https://code.djangoproject.com/wiki/AsyncProject

**Comment by patrys** [comment]
Yes, you can already use asynchronous resolvers with Django 3.1, along with `aiodataloader`, just remember to wrap all your database access functions with `asgiref.sync.sync_to_async`.

**Comment by janwout** [comment]
nice, thanks, maybe an update for documentation on use of subscriptions with django without channels would be a good idea?

**Comment by kissgyorgy** [comment]
It's already possible yes, but ariadne has nothing to do with Django.

**Comment by rafalp** [comment]
This is being discussed [here](https://github.com/mirumee/ariadne/discussions/493).
