### ISSUE TITLE
[feature] Ability to Customize JSONResponse from from ariadne.asgi.GraphQL::graphql_http_server

### ISSUE THREAD

**Issue by cancan101** [mirumee/ariadne#434]
Looking to implement a solution like outlined in [this Spectrum thread](https://spectrum.chat/ariadne/general/background-job~8f26d2af-0bdf-42b0-bf23-acdd2f687d4e?m=MTU3MjEwMjMyODEzNQ==) where the `background` is set on the `JSONResponse`, it would be nice to be able to set that that on the response without having to copy and paste code from the base class.

```python
    async def graphql_http_server(self, request: Request) -> JSONResponse:
...
        return JSONResponse(response, status_code=status_code, background=background)
```

**Comment by patrys** [comment]
If that's the only known reason to customize, I think we should just forward the background object from the request to the response object.

**Comment by cancan101** [comment]
That works. Would need to add something like:
```
    async def get_context_for_request(self, request: Any) -> Any:
        background = BackgroundTasks()
        return {"request": request, "background": background}
```
to the context.

This is all consistent with what starlette does for the graphene implementation:
https://github.com/encode/starlette/blob/b95acea973c20eea3e7cbbca42d09b1f5d4a3412/starlette/graphql.py#L98-L118

**Comment by cancan101** [comment]
I think this has been fixed?

**Comment by rafalp** [comment]
Correct, you can now customize response JSON by subclassing `asgi.GraphQL` class and overriding `create_json_response` method:

```python
    async def create_json_response(
        self,
        request: Request,  # pylint: disable=unused-argument
        result: dict,
        success: bool,
    ) -> Response:
        status_code = 200 if success else 400
        return JSONResponse(result, status_code=status_code)
```

**Comment by cancan101** [comment]
I am trying to use this now. The issue is with `create_json_response` broken out, I don't have access to the the `context_value` which I had been using like: 
```python
            return JSONResponse(
                response,
                status_code=status_code,
                background=context_value["background"],
            )
```

How would I access the context value when formulating the request? passing `background` to a response causes starlette to run that task after the response is sent.
