### ISSUE TITLE
document context_value for graphql_sync

### ISSUE THREAD

**Issue by ex-nerd** [mirumee/ariadne#435]
As far as I can tell, the `context_value` parameter for `graphql_sync()` does not handle a callable value like the normal `graphql()` does, and simply leaves me with my function instance as the context for each request, rather than the output of that function.

This is understandable but it would be nice if the documentation called this out, since the [current documentation](https://ariadnegraphql.org/docs/api-reference#configuration-options-1) simply refers the user to the `graphql()` info that clearly says [context_value can be callable](https://ariadnegraphql.org/docs/api-reference#context_value)

**Comment by rafalp** [comment]
Hi @ex-nerd, the documentation you are linking to is explicit that callable `context_value` should be evaluated on server implementation level and not in `graphql_sync`:

> If context_value is callable, it should be evaluated on higher level of abstraction (in server integration) before passing to graphql().

This is the case within the library. Callable is evaluated withing ASGI/WSGI apps and Django view.

**Comment by rafalp** [comment]
Here are places this happens:

ASGI: https://github.com/mirumee/ariadne/blob/master/ariadne/asgi.py#L92
WSGI: https://github.com/mirumee/ariadne/blob/master/ariadne/wsgi.py#L192
Django view: https://github.com/mirumee/ariadne/blob/master/ariadne/contrib/django/views.py#L133

**Comment by ex-nerd** [comment]
> Hi @ex-nerd, the documentation you are linking to is explicit that callable `context_value` should be evaluated on server implementation level and not in `graphql_sync`

I apparently need more coffee. I completely misread that statement.  Just ignore me. :)
