### ISSUE TITLE
Could you write it more detail

### ISSUE THREAD

**Issue by leminhson2398** [mirumee/ariadne#439]
I can integrate ariadne with Django by following the instruction in the ariadne document, however i don't understand the django-channels integration section, i think the sample code is a little bit short and tricky for newbies to follow. Moreover, Django today supports Asgi server out of the box. So can i add Subscription feature to my app without installing channels ?

**Comment by rafalp** [comment]
Thanks for reaching out on this.

We are using GitHub issues feature for roadmap and bug tracking, and use [Spectrum forum](https://spectrum.chat/ariadne?tab=posts) for usage questions. There's already a discussion on usage with django-channels:

https://spectrum.chat/ariadne/general/ariadne-0-12-0-django-channels~6ba4e675-0ab8-4584-92c4-012482f0bbb9
