### ISSUE TITLE
Unexpected Snake Case for Acronyms

### ISSUE THREAD

**Issue by StefanSchulz-Tesyo** [mirumee/ariadne#442]
The snake case conversion of the `snake_case_fallback_resolvers` yields unexpected results for words with multiple uppercase letters in a row, e.g.
 - `getHTTPResponse` is converted to `get_h_t_t_p_response`, or
 - `externalID` is converted to "external_i_d`.  

These are unlikely names for python attributes and I would expect the resolver to look for `get_http_response` / `external_id` instead.

Possible implementations for the camel to snake case conversions are discussed here: https://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case

**Comment by rafalp** [comment]
PR: https://github.com/mirumee/ariadne/pull/452

**Comment by BenMotz** [comment]
The change in #452 will convert `GetHTTPResponse` to `get_httpresponse`, as the case I was trying to fix was `InterfaceMACs` - which, if following  a rule that would return `get_http_response`, would yield `interface_ma_cs`.

Off the top of my head I can't think of an algorithm that would work for both (without some dubious heuristics).

**Comment by rafalp** [comment]
#452 is still good because it will convert `CanonicalURL` to `canonical_url`, reducing number of edge cases and surprises for Ariadne's users.

At the end of the day there's always `set_alias()`.

**Comment by StefanSchulz-Tesyo** [comment]
That is definitely an improvement.

I would argue the `ACRONYMOtherStuff-> acronym_other_stuff` case is more likely than `ACROnym->acronym` or `ACRONYMs -> acronyms`. But that is purely my gut feeling, I have no statistical data and I might be wrong.

**Comment by patrys** [comment]
I agree. I'd split `ABCDEFghiJklMNOpq` into `ABCDE`, `Fghi`, `Jkl`, `MN`, `Opq` (with the option to override `MACs` using custom aliases).

**Comment by taffit** [comment]
Another issue I'm currently running into: names like `phase_alpha2`, i. e. with a number at the end. Although very difficult to handle: should this result in `phase_alpha_2` or is it part of the name as in `phase_alpha2`.    
`set_alias()` helps here a lot.

**Comment by rafalp** [comment]
@taffit yup, I've opened PR adding two new cases to case converter:

- `test134` -> `test_134`
- `134test` -> `134_test`

**Comment by steezeburger** [comment]
This has broken some of my resolvers. 

This now snakecases things differently than Django and the stringcase packages. I use Django forms and previously the snakecasing matched, but now I have to add the extra `@convert_kwargs_to_snake_case` or change my form field names or some combination of both.

**Comment by rafalp** [comment]
Hey @steezeburger, sorry about that. Can you provide examples?

**Comment by steezeburger** [comment]
After updating today, I noticed a broken test where Ariadne was not automatically resolving `icd10ZCodes` from `icd10_z_codes` which worked previously. The graphql type is `ICD10ZCode` as is the Python model.

I began changing instances to `icd_10_z_codes`, but then that began breaking other tests where Django form's snakecase a graphql input value `icd10ZCodes` -> `icd10_z_codes` 

I specifically chose `icd10_z_code` at first, but after the update today I changed it to `icd_10_z_code` just for consistency sake, but then noticed it began breaking other tests.

The decorator allows things to work fine, it's just sort of non evident why I'm using the decorator there and not in any other mutations and I had to leave an awkward comment (when Django form's snakecasing previously matched Ariadnes, I didn't need to use `@convert_kwargs_to_snake_case` for mutation resolvers, and for queries the snakecase fallback resolvers also worked beautifully with Django model fields)

**Comment by steezeburger** [comment]
This worked previously:
```
# resolver function
def resolve_create_foo(_, info, form):
    form = CreateFooForm(form)
    command = CreateFooCommand(form)
    obj = command.execute()

    return obj
    
# django form class    
class CreateFooForm(django.forms.Form):
    icd10_z_codes = forms.ModelMultipleChoiceField(
        queryset=ICD10ZCodeRepository.get_queryset(),
        to_field_name='code',
        required=False)
        
# graphql input        
input CreateFooForm {
    """
    A list of ICD10 Z codes for this Foo.
    A list of values from ICD10ZCode types selected.
    """
    icd10ZCodes: [String!] 
}        
```

but then I updated the form to make all `icd_10_z_codes` instances consistent after tests began failing in some query resolvers
```
class CreateFooForm(django.forms.Form):
    icd_10_z_codes = forms.ModelMultipleChoiceField(
        queryset=ICD10ZCodeRepository.get_queryset(),
        to_field_name='code',
        required=False)
```

then this broke my existing resolver, so i had to add the decorator:

```
@convert_kwargs_to_snake_case
def resolve_create_foo(_, info, form):
    form = CreateFooForm(form)
    command = CreateFooCommand(form)
    obj = command.execute()

    return obj
```


I've got it all working fine now though.
