### ISSUE TITLE
mutation using a list of objects in from query returns a non-nullable field error

### ISSUE THREAD

**Issue by ccsv** [mirumee/ariadne#448]
Not sure if I am doing something wrong but I am getting an non-nullable field error when trying to make a bulk create with Django and Ariadne.

I have a model `Document` that just has two fields `id` and `name`. I am doing a bulk create mutation where I insert a list of dicts and return a list of objects that were created. What I expect is a return of a list of objects that is looped through by the graphql terminal to print out the objects created with the fields that are entered.

Here is the schema I am using:
```
type_defs = gql("""
   type Document {
        id:ID
        name: String!
   }
    input DocumentInput {
        id:ID
        name:String
    }

   type Mutation{
       CreateDocument(input:[DocumentInput]):[Document]
    }
    """)

   mutation = MutationType()

@mutation.field("CreateDocument")
def CreateDocument(*_, input):
    doc = [Document.objects.create(name=inputs["name"]) for inputs in input]
    return {'document': doc}
```

The error I get is:
```
 "errors": [
    {
      "message": "Cannot return null for non-nullable field Document.name.",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
```
If I print the variable `doc` in the resolver it returns a list of objects eg. `[<Document: Foo>, <Document: Bar>]` 
The context section from the terminal:

```
          "context": {
            "self": "<graphql.exec...00216F8EED8E0>",
            "return_type": "<GraphQLNonNu...ype 'String'>>",
            "field_nodes": "[FieldNode at 86:90]",
            "info": "GraphQLResolv...'/graphql/'>})",
            "path": "Path(prev=Pat...), key='name')",
            "result": "None",
            "completed": "None"
          }
```

Not sure if it is a bug or I wrote something wrong.

**Comment by rafalp** [comment]
Hi @ccsv 

Your resolver's return value is invalid. Your schema tells GraphQL query executor that you will return a list, but you return `{'document': doc}`. This means query executor iterates on dict's keys, and those will be strings that don't have `name` attr.
