### ISSUE TITLE
Async support for Django Graphql view

### ISSUE THREAD

**Issue by ccsv** [mirumee/ariadne#450]
As of Django 3.1 there is support for asynchronous views.

Can someone update the Django Graphql view to be asynchronous?

Also if I want my queries and mutations to be asynchronous what would be the best way of converting them? using the [@sync_to_async decorator](https://docs.djangoproject.com/en/3.1/topics/async/)?

**Comment by rafalp** [comment]
We plan to move `ariadne.contrib.django` into separate library with Ariadne 0.14 release. Hopefully this feature request will see more attention when that happens.
