### ISSUE TITLE
Make starlette dependency optional

### ISSUE THREAD

**Issue by frthjf** [mirumee/ariadne#458]
I'm using `ariadne` for a project that does not involve use with a web server but where it is used to parse and execute sync queries (a graphql-core+ so to speak). Therefore, I'm wondering whether it would make sense to make the starlette dependency optional since it's only required for the ASGI server as far as I can see.

**Comment by kissgyorgy** [comment]
It doesn't make any sense. ariadne is a thin layer around graphql-core, the main thing it does is the ASGI server.

**Comment by rafalp** [comment]
I'll +1 @kissgyorgy here. Our main pitch is toolkit for implementing GraphQL servers (with heavy focus on ASGI), not boilerplate for executing queries in other contexts. Dropping this would make things trickier for greater part of our userbase.

Thanks for your understanding.
