### ISSUE TITLE
Max length for Int parameter?

### ISSUE THREAD

**Issue by newtoniumx3** [mirumee/ariadne#461]
I have a mutation where a large number as a parameter seems to not be accepted. Should I pass the number as a string or?

```
status(group_id: Int): StatusResult
```

fails
```
const GET_STATUS = gql'
  query GET_STATUS {
      status(id: 1301175700782) { 
       ...
     }
  }
';
```

works
```
const GET_STATUS = gql'
  query GET_STATUS {
      status(id: 123) { 
       ...
     }
  }
';
```

**Comment by rafalp** [comment]
Please see this issue for GraphQL.js which is used by `gql` template tag: https://github.com/graphql/graphql-js/issues/292
