### ISSUE TITLE
Attribute error when attempting import

### ISSUE THREAD

**Issue by guhanvengu** [mirumee/ariadne#464]
I am trying to set up Ariadne and am currently unable to run the following import:
`from ariadne import load_schema_from_path, make_executable_schema, \
    graphql_sync, snake_case_fallback_resolvers, ObjectType`

When starting I receive the following error:
`File "/usr/local/lib/python3.6/site-packages/flask_failsafe.py", line 29, in wrapper
api               |     return func(*args, **kwargs)
api               |   File "api/dev.py", line 18, in create_app
api               |     from api.main import app
api               |   File "/app/api/main.py", line 21, in <module>
api               |     from ariadne import load_schema_from_path, make_executable_schema, \
api               |   File "/usr/local/lib/python3.6/site-packages/ariadne/__init__.py", line 1, in <module>
api               |     from .enums import EnumType
api               |   File "/usr/local/lib/python3.6/site-packages/ariadne/enums.py", line 5, in <module>
api               |     from graphql.type import GraphQLEnumType, GraphQLNamedType, GraphQLSchema
api               |   File "/usr/local/lib/python3.6/site-packages/graphql/__init__.py", line 42, in <module>
api               |     from .version import version, version_info, version_js, version_info_js
api               |   File "/usr/local/lib/python3.6/site-packages/graphql/version.py", line 47, in <module>
api               |     version_info = VersionInfo.from_str(version)
api               | AttributeError: type object 'VersionInfo' has no attribute 'from_str'`

Python version 3.6
ariadne version from requirements.txt: 0.12.0

The code being referenced from the graphql package(referenced below) is able to run in isolation as well.
`import re
from typing import NamedTuple
__all__ = ["version", "version_info", "version_js", "version_info_js"]
version = "3.1.2"
version_js = "15.1.0"
_re_version = re.compile(r"(\d+)\.(\d+)\.(\d+)(\D*)(\d*)")
class VersionInfo(NamedTuple):
    major: int
    minor: int
    micro: int
    releaselevel: str
    serial: int
    @classmethod
    def from_str(cls, v: str) -> "VersionInfo":
        groups = _re_version.match(v).groups()  # type: ignore
        major, minor, micro = map(int, groups[:3])
        level = (groups[3] or "")[:1]
        if level == "a":
            level = "alpha"
        elif level == "b":
            level = "beta"
        elif level in ("c", "r"):
            level = "candidate"
        else:
            level = "final"
        serial = groups[4]
        serial = int(serial) if serial else 0
        return cls(major, minor, micro, level, serial)
    def __str__(self) -> str:
        v = f"{self.major}.{self.minor}.{self.micro}"
        level = self.releaselevel
        if level and level != "final":
            v = f"{v}{level[:1]}{self.serial}"
        return v
version_info = VersionInfo.from_str(version)
version_info_js = VersionInfo.from_str(version_js)`

Any help would be appreciated, let me know what other info I can provide

**Comment by rafalp** [comment]
Are you sure `graphql-core` package is installed correctly in your env? `VersionInfo` implemented in it has had `from_str` since 2019

**Comment by guhanvengu** [comment]
I had not previously installed graphql-core, so I let ariadne install it as a dependency.
After that failed I explicitly declared it in the requirements.txt to be between 3.0.0 and 3.1.0 I believe as that seemed to be what was declared. I've also tried newer and older versions, but had errors on installing due to dependency mismatches

**Comment by guhanvengu** [comment]
Additionally when running that `versionInfo` code in isolation, it is able to run no problem

**Comment by rafalp** [comment]
I'm unable to repro this issue. 😢 

If you are still experiencing this, please create GH repo with reproduction, and I'll re-open.
