### ISSUE TITLE
Provide gql() utility function for wrapping/validating SDL on spot

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#47]
Currently, syntax errors in SDL are raised by `graphql()`, which itself is called deep in GraphQL server initialization logic. This makes it trickier to trace back to invalid type definitions - especially in complex projects.

Ariadne could provide `gql()` utility function that would allow developers to mark pieces of code as SDL, and validate those SDL strings on scripts execution, raising execetions with traceback pointing to point of definition, making those easier to find and debug:

```python
from ariadne import gql

type_defs = gql("""
    type User {
        username: String!
        posts: [Post!]
        threads: [Thread!]
        follows [User!]
        likes: [Post!]
    }
""")
```

Above code would raise `GraphQLSyntaxError` pointing to `type_defs`, instead of somewhere in GraphQL server initialization logic.

This approach adds one more advantage: If we know that strings wrapped with `gql()` are SDL, we can develop a pattern for GraphQL syntax highlighters for IDEs to use to color GraphQL syntax in Python projects.

Lastly, `gql()` should pass through the strings, because our current modularization implementation is very simple: internally it does string joining using `\n` as glue. We'll rather avoid reimplementing it to create custom mechanism operating on `ast`'s.

**Comment by wordyallen** [comment]
so how do I add this to my ide?

**Comment by rafalp** [comment]
AFAIK at the moment this is only supported by the Visual Studio Code with [Apollo GraphQL plugin](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo).
