### ISSUE TITLE
Support for AsyncIterable resolvers

### ISSUE THREAD

**Issue by Jamie-Chang** [mirumee/ariadne#486]
Currently async resolvers for arrays are async functions that return an iterable. 

There seem to be a lack for support for AsyncIterator resolvers. For example, using motor to query a mongo collection:
```
async def resolve_users(*_):
    async for document in collection.find({}):
        yield document
```
Of course, a work around would be to fetch all documents first, but supporting the async iterator / generator would be a much nicer way to do it.

**Comment by rafalp** [comment]
Hey,

We don't implement GraphQL query executor ourselves. Instead we rely on library called [GraphQL core](https://github.com/graphql-python/graphql-core) for this.

Please post this feature request on their repo instead.
