### ISSUE TITLE
Link to community when opening issue needs to be updated

### ISSUE THREAD

**Issue by bartenra** [mirumee/ariadne#527]
![image](https://user-images.githubusercontent.com/77667589/113692803-374aa400-96ce-11eb-9fa2-3ba44fa921b4.png)

The "Open" button here still leads to Spectrum, not GitHub Discussions.

**Comment by rafalp** [comment]
Woot, I've updated link name and description but not the URL itself 😅

For reference, here's file that needs update: https://github.com/mirumee/ariadne/blob/master/.github/ISSUE_TEMPLATE/config.yml

**Comment by kuchichan** [comment]
Hello!
First of all, thanks for reporting! I forgot to link the issue to PR: https://github.com/mirumee/ariadne/pull/530, which has been merged. From our point of view, issue can be closed.
