### ISSUE TITLE
API descriptions

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#54]
GraphQL supports item descriptions, but currently, Ariadne provides no way to set those, and neither does `GraphQL-Core` version we are using.

Ideally, we should provide two ways to set item descriptions:

- if resolver has docstring, we should use it
- add `description=` kwarg to `make_executable_schema` & friends that would take dict of dicts and would override items descriptions based on that. We could read special key (eg. `__description`) to get description for type. This approach should also support modularization.

**Comment by patrys** [comment]
I'm all for making descriptions part of schema, not implementation. Using mock resolvers should not alter the results of introspection.

**Comment by rafalp** [comment]
Ok. As descriptions are already implemented by GraphQL Core Next, closing this issue should involve adding documentation for descriptions.
