### ISSUE TITLE
convert_kwargs_to_snake_case only recursive if placed after field decorator

### ISSUE THREAD

**Issue by qw-in** [mirumee/ariadne#542]
Given this input schema
```gql
input NestedPayload {
  camelCase: String
}

input InputPayload {
  camelCase: String
  nested: NestedPayload!
}

type Mutation {
  field(input: InputPayload!): String
}
```

When placed in this order, only `InputPayload` will have field case converted
```py
@convert_kwargs_to_snake_case
@mutation.field('field')
def resolve(_, info, input):
# Input is
{'camel_case': None, nested: {'camelCase': None}}
```

When placed in this order, both will have field case converted
```py
@mutation.field('field')
@convert_kwargs_to_snake_case
def resolve(_, info, input):
# Input is
{'camel_case': None, nested: {'camel_case': None}}
```

**Comment by rafalp** [comment]
Thank you for this report but it's a feature, per our [docs](https://ariadnegraphql.org/docs/resolvers):

> The @query.field decorator is non-wrapping - it simply registers a given function as a resolver for the specified field and then returns it as it is.

For reverse order to work we would have to do some sort of magic around resolvers that `@convert_kwargs_to_snake_case` would be aware of, and we explicitly don't want that in Ariadne.

Thanks!

**Comment by qw-in** [comment]
@rafalp thanks!

Would it be possible to error if the placement is wrong? Having it partially work was the most confusing part

**Comment by rafalp** [comment]
This would also require magic, but would also break the behavior when function is used with `set_field`:

```python
# in somewhere.py
@convert_kwargs_to_snake_case
def resolver(...):
    ...

# in schema.py
from .somewhere import resolver

type.set_field("myfield", resolver)
```
