### ISSUE TITLE
Remove reference to (deprecated) AsgiHandler

### ISSUE THREAD

**Issue by bartenra** [mirumee/ariadne#585]
`AsgiHandler` has been deprecated: https://channels.readthedocs.io/en/stable/releases/3.0.0.html?highlight=AsgiHandler#deprecations

It's still mentioned [in the docs](https://ariadnegraphql.org/docs/django-integration.html)

**Comment by rafalp** [comment]
I don't think we have anyone on team familiar with Django async who could do this for us. 🤔

Pull request updating this doc is welcome. :)

**Comment by bartenra** [comment]
Here is what we are doing:

```py
from channels.routing import ProtocolTypeRouter, URLRouter
from django.core.asgi import get_asgi_application

application = ProtocolTypeRouter(
    {
        # Django's ASGI application to handle traditional HTTP requests
        "http": get_asgi_application(),
        # WebSocket chat handler
        "websocket": URLRouter(
            [path("graphql/", AuthenticatedChannel(schema, debug=True))]
        ),
    }
)
```

Where `AuthenticatedChannel` is just a class that inherits from `ariadne.asgi.GraphQL` that handles authentication for websocket connections.

**Comment by rafalp** [comment]
I'm closing this as we've passed Django support to 3rd party app and our Django docs will be updated to only direct people to 3rd party lib.

Please see #656 for the context.
