### ISSUE TITLE
Lack of documentation for subscriptions

### ISSUE THREAD

**Issue by ArtyomKaltovich** [mirumee/ariadne#648]
Hello.

Thank you for your library, I am new here, so sorry for the probably dumb question.

I am learning https://ariadnegraphql.org/docs/subscriptions.html example, but I can't find out how to run it. :)

I guess the example lacks the "How to Run" section.

I run the app with 

    if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)

But I still can't figure out how to subscribe

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/10615183/129367107-1ab5e084-8ea0-4c53-a74d-a6f33fb12a8b.png">

Regards.

**Comment by rafalp** [comment]
Hi. Do you mean that when you enter `subscribe { counter }` it doesn't yield any query results?
