### ISSUE TITLE
Django contrib module removed in 0.14.0 but still packaged in the wheel

### ISSUE THREAD

**Issue by tonysyu** [mirumee/ariadne#739]
I noticed that the 0.14.0 release removed `ariadne.contrib.django`, but that module is still packaged as part of the wheel on PyPI. It doesn't seem to be present in the sdist uploaded PyPI, though (as expected). Not a big deal, but it led to some brief confusion when comparing a local copy of 0.14.0 with the tagged version on github.

**Comment by aitorres** [comment]
I just came here because of this very same confusion after a recent update of `ariadne` to `0.14.0`, expecting `ariadne.contrib.django` not to be there... but it still was.

**Comment by rafalp** [comment]
Yeah, looks like it was there in build dir when I've ran twine. I'll release 0.14.1 sometime next week to resolve this.

**Comment by rafalp** [comment]
I've fixed this in 0.14.1

**Comment by rafalp** [comment]
@the-papi considered you've had 3 months to adapt to this change (which we've communicated well in advance), I find your tone unjustified. ☹️
