### ISSUE TITLE
Documentation regarding GraphQL.js version outdated

### ISSUE THREAD

**Issue by j-riebe** [mirumee/ariadne#741]
The documentation of compatible GraphQL.js version is outdated.

[Ariadne-Docu](https://github.com/mirumee/ariadne/blob/2393fb8d2b60fb948ba4f251f7d8c01457941663/README.md?plain=1#L23) states:
> Compatibility with GraphQL.js version 14.4.0.

As ariadne uses [graphql-core](https://github.com/graphql-python/graphql-core/blob/28772a2f3529ac2772e616e24ccb76c085f1e87b/README.md?plain=1#L15) version 3.1.6 it already support GraphQL.js version 15.5.1:
> The current version 3.1.6 of GraphQL-core is up-to-date with GraphQL.js version 15.5.1.

**Comment by rafalp** [comment]
Thanks for reporting this. PR welcome :)

**Comment by rafalp** [comment]
Thanks!
