### ISSUE TITLE
Error in subscription doc?

### ISSUE THREAD

**Issue by ArtyomKaltovich** [mirumee/ariadne#745]
In https://ariadnegraphql.org/docs/subscriptions.html#using-on_connect-to-access-connection-s-parameters documentation there is the following example

```
    ...

    def context_value(request):
        context = {}
    
        if request.scope["type"] == "websocket":
            # request is an instance of WebSocket
            context.update(websocket.scope["connection_params"])  # Unresolved reference 'websocket' (my remark)
        else:
            context["token"] = request.META.get("authorization")
    
        return context
 
   ...
```

I guess it should be 

```
    context.update(request.scope["connection_params"])
```

As `websocket` name isn't defined in the function scope?

**Comment by rafalp** [comment]
It seems like so. PR fixing this would be appreciated!

**Comment by ArtyomKaltovich** [comment]
Oh, it in the different project, I will close this issue and open it there then.

Thank you.
