### ISSUE TITLE
Raising error in resolver of non-nullable field returns None for entire root object

### ISSUE THREAD

**Issue by pylipp** [mirumee/ariadne#746]
Consider the following MWE about having an error raised in a nested resolver

```python
from ariadne import ObjectType, QueryType, make_executable_schema
from ariadne.asgi import GraphQL
from starlette.applications import Starlette
from starlette.middleware.cors import CORSMiddleware


class AuthzError(Exception):
    extensions = {"code": "UNAUTHORIZED"}

type_def = """
    type Query {
        child: Child
    }
    type Child {
        id: ID!
        parent: Parent!
    }
    type Parent {
        id: ID!
    }
"""

query_type = QueryType()
child_type = ObjectType("Child")

@query_type.field("child")
def resolve_child(*_):
    return {"id": 1, "parent": {"id": 2}}

@child_type.field("parent")
def resolve_child_parent(child_obj, info):
    raise AuthzError("No permission to access parent")

debug = False
schema = make_executable_schema(type_def, query_type, child_type)
graphql_server = GraphQL(schema, debug=debug)

app = Starlette(debug=debug)
app.add_route("/graphql/", graphql_server)
app.add_websocket_route("/graphql/", graphql_server)
app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["POST"],
        allow_headers=[
                    "accept",
                    "accept-language",
                    "content-language",
                    "content-type",
                    "x-apollo-tracing",
                ],
)
```

Running the query `query { child { id parent { id } } }` returns `{"data": {"child": None}}`. I would expect `{"data": {"child": {"id": 1}}}`. 
(When making the `Child.parent` field nullable, one obtains `{"data": {"child": {"id": 1, "parent": None}}}` which is expected).

Is this the desired behavior? I was expecting to have at least the non-erroneous fields (i.e. `id`) returned in `data`. OTOH the schema requires `Parent!`, hence maybe the server cannot return `{"parent": None}`?

The closest issue I could find was #339 . Using ariadne `0.14.0`.

**Comment by rafalp** [comment]
Hi. Query executor is out of scope for Ariadne as its implemented by graphql-core package, but this seems to be part of spec:

> Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.

**Comment by pylipp** [comment]
I see, thank you! Leaving a [link to the spec](http://spec.graphql.org/October2021/#sec-Handling-Field-Errors) for reference.
