### ISSUE TITLE
Latest GraphQL breaks validate_query

### ISSUE THREAD

**Issue by lxop** [mirumee/ariadne#769]
Version 3.2.0 of dependency graphql-core changes the type of `graphql.validation.specified_rules.specified_rules` from a `FrozenList` to a tuple. Ariadne's `validate_query` includes the line
```python
        supplemented_rules = specified_rules + list(rules)
```
which now breaks with the error
```
TypeError: can only concatenate tuple (not "list") to tuple
```

Without looking into it too much, I assume just changing the line to
```python
supplemented_rules = list(specified_rules) + list(rules)
```
would fix the problem without introducing a backward-incompatibility with graphql < 3.2.0.

[Here](https://github.com/graphql-python/graphql-core/commit/b9423b74ca9d22d009a1a4633b38b2bcd06c604b#diff-d55e85763a00fce801a03edaf87c696d9c389fe93f843ddc481f875bd4ef744f) is the commit that changed the type, and it was released in [v3.2.0rc4](https://github.com/graphql-python/graphql-core/releases/tag/v3.2.0rc4).

It would also be worthwhile to limit the graphql-core version compatibility to pin to a minor release since that package notes that breaking changes can be introduced when the minor version changes.

**Comment by rafalp** [comment]
Oh, we should update setup.py to lock GraphQL version at <3.2.

In meantime adding `graphql-core<3.2` to requirements manually should fix this?

**Comment by gdalmau** [comment]
@lxop Since https://github.com/mirumee/ariadne/pull/774 will be included in the next release, can we rename the title of this issue to "Compatibility with graphql-core 3.2"?

/cc @rafalp

**Comment by gdalmau** [comment]
@lxop I meant to convert this issue to make ariadne compatible with graphql-core 3.2, where the issue currently described is one of the things that need to be fixed (if there are any others).

> But it could potentially be changed to "Incompatible with graphql-core 3.2" if that helps?

I agree :)

**Comment by rafalp** [comment]
Fixed on master

**Comment by gdalmau** [comment]
For reference purposes, it was fixed in https://github.com/mirumee/ariadne/pull/796
