### ISSUE TITLE
Use `execute_sync` in `graphql_sync`

### ISSUE THREAD

**Issue by bartenra** [mirumee/ariadne#823]
`graphql_sync` should use `execute_sync` instead of `execute`.

I run my code in a synchronous context, but a resolver was identified as asynchronous due to the fact that GraphQL core does a simple `hasattr(value, "__await__")` check instead of using `inspect.isawaitable`. This caused a false positive.

However, when using `graphql_sync` I expect that this check does not even happen. Consider using [`execute_sync`](https://github.com/graphql-python/graphql-core/blob/27768d3faac5bb8ebb2c6a151a7192b7fa498f2f/src/graphql/execution/execute.py#L1061) instead.

**Comment by rafalp** [comment]
Thanks for reporting this, would you like to open an PR with the fix?
