### ISSUE TITLE
Implement graphql-ws protocol support

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#837]
Currently Ariadne implements `subscription-transport-ws` protocol which Apollo has deprecated and replaced with [graphql-ws](https://github.com/enisdenjo/graphql-ws).

We should either update `ariadne.asgi.GraphQL` to graphql-ws or refactor it to make WebSocket support handled via strategy pattern, eg:

```python
app = GraphQL(schema, websocket=GraphQLWS(options))
```

**Comment by eugeneyalansky** [comment]
There is a need for me to implement. @rafalp Would you like to share some thoughts so we can discuss my contribution?

**Comment by rafalp** [comment]
Hey @eugeneyalansky. I am open to making Ariadne support websocket protocols through strategy pattern as described in first post. So you could implement it yourself and then pass it to Ariadne.

**Comment by eugeneyalansky** [comment]
I'm thinking of subprotocols strategies. 
I'd like also to cover queries and mutations based on WS transport, I've checked the source code on related PRs. 

The protocol specifies how to handle queries and mutations, but on the other hand, distinguishing it from subscriptions without parsing the query into a document seems challenging.

**Comment by rafalp** [comment]
I think we can assume here that if connection was made over the websocket, its going to be subcription. Ariadne's `subscribe` method will do the checking if thats indeed a fact for you.

**Comment by pigletto** [comment]
@rafalp @eugeneyalansky In fact I've already started working on adding graphql-transport-ws protocol (this is the correct protocol name, while project is graphql-ws) to Ariadne. See my fork: https://github.com/pigletto/ariadne/tree/graphql-transport-ws-protocol

Some details about this implementation: The protocol detection is done automatically. Running queries and mutations is also done (for both protocols). I consider this implementation almost done - currently I'm writing tests and doing some minor fixes. Some ideas are borrowed from Strawberry project

**Comment by eugeneyalansky** [comment]
@pigletto What a save, checking out your changes

It's kind of confusing namespacing 😑

graphql-ws = graphql_transport_ws
subscriptions-transport-ws = graphql-ws

**Comment by rafalp** [comment]
@pigletto this is amazing work!

My only suggestion is to make protocols provided to `asgi.GraphQL` through construction options so they are easy to customize by devs having non-standard use cases. Making API easy for customization if you need something Ariadne doesn't provide is one of design paradigms we are following here.

Also would you be ok with me assigning this issue to you?

**Comment by pigletto** [comment]
@rafalp thanks for the feedback! Yup, feel free to assign me to this issue

**Comment by eugeneyalansky** [comment]
minor question, would it be appropriate to pass parsed document instead of a query to `subscribe` / `graphql` methods. 
Its usages a very narrow in the project, but will take some additional work to adjust tests.

**Comment by pigletto** [comment]
> minor question, would it be appropriate to pass parsed document instead of a query to `subscribe` / `graphql` methods. Its usages a very narrow in the project, but will take some additional work to adjust tests.

@eugeneyalansky what do you mean by adjusting tests? Currently all the tests on my fork are passing

**Comment by rafalp** [comment]
@eugeneyalansky can you share more on your usecase? What client are you planning to use that runs regular queries and mutations over websocket?

**Comment by pigletto** [comment]
@rafalp it's the same as #341 and it is already done in my fork for both protocols

**Comment by rafalp** [comment]
Oh, right, I've forgot about that one.

**Comment by rafalp** [comment]
Relased in 0.16
