### ISSUE TITLE
Pass in data to get_context_for_request

### ISSUE THREAD

**Issue by cancan101** [mirumee/ariadne#843]
That way you can write something like:
```python
    async def get_context_for_request(
        self,
        request: Any,
        *, data: Dict[str, Any] = None
    ) -> Any:
        if callable(self.context_value):
            context = self.context_value(request)
            if isawaitable(context):
                context = await context
            return context

        data = data or {}

        query: Optional[str] = data.get("query")
        variables: Optional[Dict[str, Any]] = data.get("variables")
        operation_name: Optional[str] = data.get("operationName")

        return self.context_value or {
            "request": request,
            "variables": variables,
            "operation_name": operation_name,
            "query": query,
       }
```

that way the tracing extension can access `operation_name`, `variables`, and `query` which is very helpful metadata context.

**Comment by rafalp** [comment]
Is there a reason you can't do this by pulling JSON from request custom `context_value` callable? By the point it's called by Ariadne JSON payload was already validated.

**Comment by cancan101** [comment]
I am not totally sure what you mean? do you mean something like:
```
async def context_value(request):
         data = await self.extract_data_from_request(request)
        query: Optional[str] = data.get("query")
        variables: Optional[Dict[str, Any]] = data.get("variables")
        operation_name: Optional[str] = data.get("operationName")
       return {
           "request": request,
            "variables": variables,
            "operation_name": operation_name,
            "query": query,
}
```
the answer would be to avoid calling `extract_data_from_request` twice on each request.

**Comment by rafalp** [comment]
I've meant accessing `request.json()` second time. `extract_data_from_request` really only does validation on data.

On sidenote, wouldn't it make it more sense to pass data to `Extension.request_started`?

**Comment by cancan101** [comment]
Changing the signature of `request_started` seems more problematic since that is very much a public API. Further `request_started` already gets the `context` which overall seems like a more natural place to attach and send this information. `extract_data_from_request` does look to call `json()` again. Not sure if that underlying parsing is cached.

**Comment by rafalp** [comment]
TBH it's going to be less problematic than suggested change, which would require us to change signature for `context_value` callable to have parity between default behavior for context creation and custom one.

**Comment by rafalp** [comment]
IMHO this is another issue in the "we need better extension system" saga, not "we need to put data in default context" ;)

**Comment by rafalp** [comment]
Turns out this would be useful for root value resolver in our GraphQL proxy implementation, so I'll give it a try.

**Comment by rafalp** [comment]
I've did second look at this and I think parsing `data` to context callable is doable, so I'll split root resolver work in separate task and take care of both of those.

**Comment by rafalp** [comment]
I've also considered passing data to extensions directly, but I feel that added more complexity than it was worth it.
