### ISSUE TITLE
Apollo Federation 2 Support

### ISSUE THREAD

**Issue by maspling** [mirumee/ariadne#846]
Since Apollo Federation 2 is now released and introduced a few new directives and some optional fields, is there any current efforts in the project to support those?

What is new in Federation 2: https://www.apollographql.com/docs/federation/federation-2/new-in-federation-2

Compatibility Chart: https://github.com/apollographql/apollo-federation-subgraph-compatibility

**Comment by rafalp** [comment]
There's no work going on our side for getting this into Ariadne, but it would be great to support it, either in core or as 3rd party library.

Marking this as "help wanted" for now.

**Comment by lleadbet** [comment]
Just filed a PR for this above to avoid having to shim in support per subgraph. :)

**Comment by dariuszkuc** [comment]
Federation support was added in #861 - should this issue be closed?

**Comment by rafalp** [comment]
@dariuszkuc Yup, thanks!
