### ISSUE TITLE
`make_federated_schema` extremely slow when schema includes block comments

### ISSUE THREAD

**Issue by patrickodpt** [mirumee/ariadne#848]
As the title states, the `make_federated_schema` call becomes progressively slower with block comments as they increase in length. This issue was noticed when moving from 0.14.0 to 0.15.0. I believe it's related to the new regular expressions including in 0.15.0 and absent in 0.14.0.

**Comment by patrickodpt** [comment]
Looks like [this PR](https://github.com/mirumee/ariadne/pull/847#issue-1208666126) may fix it.

**Comment by rafalp** [comment]
Fixed in 0.15.1
