### ISSUE TITLE
The `purge_schema_directives` function chokes on the `repeatable` keyword

### ISSUE THREAD

**Issue by dchambers** [mirumee/ariadne#876]
An example of standard Apollo directive that uses `repeatable` is `@tag`, which has the following definition (in Federation v1):

```
directive @tag(name: String!) repeatable on FIELD_DEFINITION | INTERFACE | OBJECT | UNION
```

The `@tag` directive can be [applied to more parts of the schema in Federation v2](https://www.apollographql.com/docs/studio/contracts/#federation-1-limitations), but the `repeatable` keyword is already common to the definition of this directive in both Fed v1 and Fed v2.

**Comment by itamar82** [comment]
do you have an example schema that is problematic? 

Just tried:


```
extend schema @link(url: "https://specs.apollo.dev/federation/v2.0")
    
        type Query
        
        type Product @tag(name: "test") {
            upc: String!
            name: String
            price: Int @tag(name: "test") @tag(name: "test2")
        }
```

and seems to work fine

**Comment by rafalp** [comment]
I've added test case that uses given schema, and there's no hangup so I guess this issue was resolved in meantime:

```graphql
type Query

type Product @tag(name: "test") @tag(name: "test3") {
    upc: String!
    name: String
    price: Int @tag(name: "test2") @tag(name: "test4")
}

```
