### ISSUE TITLE
GraphQL API explorer

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/ariadne#9]
It is a standard among other GraphQL frameworks to ship a built-in GraphQL API explorer. We should consider adding one in Ariadne as well:
- [GraphiQL](https://github.com/graphql/graphiql)
- [graphql-playground](https://github.com/prismagraphql/graphql-playground)

Probably we should choose the second one as it allows to set headers and contains queries history.

**Comment by rafalp** [comment]
Having worked with both, I'm +1 for Playground.

Support for tabs (so eg. you can run mutation in first tab and query to test changes in second) as well as support for custom HTTP headers (making it easier to test custom auth schemes) are great improvements over the GraphiQL.
