### ISSUE TITLE
How are Interger Enum handled?

### ISSUE THREAD

**Issue by ccsv** [mirumee/ariadne#904]
How does Ariadne handle Enums with integers? I am working with a django model which stores the enums in the database as Ints. I asked on Stackoverflow but got no responses

https://stackoverflow.com/questions/73225381/ariadne-graphql-displaying-django-choices-in-query

In the [Strawberry](https://strawberry.rocks/docs) graphql library I would do this:

```
import strawberry
from enum import Enum

@strawberry.enum
class Status(Enum):
  Open = 1
  Pending = 2
  Completed = 3
```

Is there an equivalent or should I just avoid them and store the values into the database as another model.

**Comment by rafalp** [comment]
You need to tell Ariadne how to map enum values to enum. Your example from StackOverflow misses passing of `EnumType ` to `make_executable_schema`:

```python
class Status(int, Enum):
  Open = 1
  Pending = 2
  Completed = 3


status_enum = EnumType("Status", Status)

type_defs = gql(
    """
    type Query {
        status: Status
    }

    enum Status {
        Open
        Pending
        Completed
    }
    """
)


query_type = QueryType()


@query_type.field("status")
def resolve_status(*_):
    return 2


schema = make_executable_schema(type_defs, query_type, status_enum)
```

Now if you query for `{ status }` you will get `{ "status": "Pending" }` as result.

I don't know how compliant with regular enums Django's `Choice` types are but maybe initializing `EnumType` with your choices will be enough? Eg:

```python
status_enum = EnumType("Status", issue_status)
```

**Comment by ccsv** [comment]
@rafalp  Thanks it works great for query I think I just missed out the `int` in the Status class. It looks like using in `class Status(enum.IntEnum):` is also equivalent
