### ISSUE TITLE
Cost validator throws duplicate error for an invalid input

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#935]
### Discussed in https://github.com/mirumee/ariadne/discussions/934

<div type='discussions-op-text'>

<sup>Originally posted by **jayeshv** September 30, 2022</sup>
Consider the following app

```
from ariadne import QueryType, ScalarType, gql, make_executable_schema
from ariadne.asgi import GraphQL
from ariadne.validation import cost_directive, cost_validator

type_defs = gql("""
    scalar MyScalar

    type Query {
      test(myInput: MyScalar!): String
    }
""")

query = QueryType()
my_scalar = ScalarType("MyScalar")

@my_scalar.value_parser
def validate_myscalar(value):
    if value == "a":
        raise ValueError("Invalid myscalar")
    return value


@query.field("test")
def resolve_hello(_, info, **kw):
    return "hello"


schema = make_executable_schema([type_defs, cost_directive], query, my_scalar)
app = GraphQL(schema, debug=False, validation_rules=[cost_validator(maximum_cost=5)])

```
for the following query, it generates two error objects.

```
query test {
  test(myInput: "a") 
}
```
```
{
  "error": {
    "errors": [
      {
        "message": "Argument 'myInput' has invalid value \"a\".\n\nGraphQL request:2:17\n1 | query test {\n2 |   test(myInput: \"a\")\n  |                 ^\n3 | }"
      },
      {
        "message": "Expected value of type 'MyScalar!', found \"a\"; Invalid myscalar",
        "locations": [
          {
            "line": 2,
            "column": 17
          }
        ]
      }
    ]
  }
}
```
Isn't the first error created by the cost_validator a redundant one? This duplicate error happens only with the extra validator. 
ariadne version  0.16.1</div>

**Comment by rafalp** [comment]
@jayeshv Thanks for reporting this. The reason there are two errors here is because there are two validators tat query fails against:

GraphQL core's query validator that validates query against schema
Query cost validator that expected value of one type but got another
I'm thinking that proper fix here is to only run custom validators like price check only after standard validation has passed and we know there's nothing specially funky with the query.

**Comment by jayeshv** [comment]
> I'm thinking that proper fix here is to only run custom validators like price check only after standard validation has passed and we know there's nothing specially funky with the query.

I too think that is the right fix. I made a rough fix here without knowing the entire code flow.
https://github.com/mirumee/ariadne/pull/936
What I did was to avoid reporting errors other than the cost one. 
With this fix, it is throwing both the validation and the cost error. 

I like this behavior too, but I think what you are suggesting is to remove catching that exception.

**Comment by rafalp** [comment]
I'll experiment with this next week to see how we can handle this issue better. I'm not feeling comfortable about eating errors that may be caused by potentially serious issues elsewhere in validator.

**Comment by rafalp** [comment]
Apologies for the delay, but I've finally investigated this. I think that we should move the logic from GraphQL core's [`validate`](https://github.com/graphql-python/graphql-core/blob/main/src/graphql/validation/validate.py#L20) util into Ariadne's `validate_query` util, and run validators in two loops:

- `specified_rules` validation (rules that verify Query following GraphQL Spec)
- `custom_rules` validation (verifies that query is compliant with custom rules like query cost)

This `custom_rules` validation should only occur if `specified_rules` validation passed.

**Comment by rafalp** [comment]
Alternative solutions:

- Make errors raised by cost validator same as ones raised by spec validators, then dedupe validation errors.
- Make `max_errors` customizable on `GraphQL` apps so you can limit number of validation errors to say, one.

**Comment by rafalp** [comment]
Punting this from 0.17, I don't feel this is big issue that should prevent the release.

**Comment by jayeshv** [comment]
@rafalp Thank you.
Btw, the cost validator looks somewhat buggy in a few more ways. 

You can not pass arguments to a query using variables. 
eg:  consider the following script to post a query

```
query_str = """
       query getTest($val: Int!) {
          test(val: $val) 
        }
"""
query = gql(query_str)
requests.post("http://127.0.0.1:8000",  json={"query": query, "variables": {"val": 3}})
```
This will throw the following error with the cost validator enabled, but works otherwise.
"message":"Argument \'val\' of required type \'Int!\' was provided the variable \'$val\' which was not provided a runtime value

**Comment by rafalp** [comment]
Query cost validator requires extra setup to support variables, its documented here:

https://ariadnegraphql.org/docs/query-validators#exposing-query-variables-to-cost_validator

**Comment by rafalp** [comment]
Unless this is shown to be a terrible world-ending issue, I am closing this with "current approach is better than proposed alternatives" resolution.
