### ISSUE TITLE
Add explorer for Apollo

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#947]
I'm not sure.. the github code says MIT..

https://www.apollographql.com/docs/studio/explorer/sandbox/
You can use Sandbox offline and without an Apollo account. You also [embed Sandbox](https://www.apollographql.com/docs/studio/explorer/sandbox/#embedding-sandbox) on your own website.

https://github.com/apollographql/embeddable-explorer/blob/main/LICENSE

_Originally posted by @davlee1972 in https://github.com/mirumee/ariadne/issues/600#issuecomment-1275332475_

**Comment by davlee1972** [comment]
I'll pick this one up..

**Comment by davlee1972** [comment]
Pull request
https://github.com/mirumee/ariadne/pull/948

**Comment by rafalp** [comment]
Closed by #948
