### ISSUE TITLE
OpenTracingExtension with refactored ariadne.asgi.GraphQL?

### ISSUE THREAD

**Issue by plannigan** [mirumee/ariadne#951]
[v0.16](https://github.com/mirumee/ariadne/blob/master/CHANGELOG.md#0160-2022-09-08) refactored `ariadne.asgi.GraphQL` and adjusted to receive handlers instead of extensions. However, it looks like the [open-tracing documentation](https://github.com/mirumee/ariadne-website/blob/0579e8a4740260606f743e5936f8ba73afe7568a/docs/open-tracing.md?plain=1#L18) was not updated. Open tracing is [still implemented as an extension](https://github.com/mirumee/ariadne/blob/0fca6bb601fa4827741d1e3f05b0138801e134f8/ariadne/contrib/tracing/opentracing.py#L18), so it seems like the functionality might be currently broken.

**Comment by rafalp** [comment]
Just to be clear, this functionality was never broken. You simply need to pass extension to handler's `extensions` option:

```python

app = GraphQL(
    schema,
    http_handler=GraphQLHTTPHandler(
        extensions=[opentracing_extension()],
    ),
)

```

**Comment by rafalp** [comment]
Updated docs.
