### ISSUE TITLE
Support Starlette 0.21.0

### ISSUE THREAD

**Issue by adriangarrote** [mirumee/ariadne#956]
Starlette 0.21.0 fix important issues on the BaseHttpMiddleware side. 

https://github.com/encode/starlette/pull/1715
https://github.com/tiangolo/fastapi/issues/4544

**Comment by rafalp** [comment]
I am thinking that we should set Starlette dependency in Ariadne at <1.0. I don't remember Starlette's release in recent years that broke Ariadne, seeing how its used in ASGI GraphQL app for parsing ASGI request.

**Comment by aklim007** [comment]
@rafalp Please release with this fix, it blocks the fastapi update in my project.

**Comment by rafalp** [comment]
@aklim007  Noted, next week I'll make 0.17 release that is branched from 0.16.1 release and bumps starlette dependency to <1.0 and I'll make current work on master target 0.18 release instead.

**Comment by rafalp** [comment]
Beta release is up on PyPi: `0.17.0b2`

I'll test it against few projects and if things seem to be ok, I'll release stable 0.17 tomorrow.
