### ISSUE TITLE
Fragments not implemented?

### ISSUE THREAD

**Issue by simanlaci** [mirumee/ariadne#987]
Any plan of implementing Fragments?

**Comment by rafalp** [comment]
Can you explain what you mean? Fragments are already fully supported by Ariadne.

**Comment by rafalp** [comment]
Closing due to no response from reporter. I'll be happy to re-open when more context is available.

**Comment by nivedano** [comment]
> Can you explain what you mean? Fragments are already fully supported by Ariadne.
Could you explain how to use it?

1. The docs at https://ariadnegraphql.org/docs/intro have no single mention of "fragment".
2. Executable schema (result of `make_executable_schema`) does not have fragments, defined in graphql schema file, parsed to any `type_map` objects.
3. An attempt to use fragment in a query result in "Unknown fragment '.....'." error

So I cannot see them working or even present in the library.

**Comment by rafalp** [comment]
@nivedano GraphQL fragments are **part of queries**, not schema. Passing fragment to the `make_executable_schema` will not work for this reason. Its also why GraphiQL will not show them.

> An attempt to use fragment in a query result in "Unknown fragment '.....'." error

Define fragment in same payload as query, and **it will work**.

**Comment by nivedano** [comment]
> @nivedano GraphQL fragments are **part of queries**, not schema. 

You're right, thanks for the lecture. It makes fragments less useful, however.

Nevertheless, it makes sense to mention this capability in the Ariadne's documentation as well.

**Comment by rafalp** [comment]
> It makes fragments less useful, however.

You can pre-define fragments on the server by implementing a custom query parser, but there's no documentation for that, so its a moot currently. ;)

If you feel this should be supported in GraphQL proper, you can submit a [specification change proposal](https://github.com/graphql/graphql-spec/issues).

> Nevertheless, it makes sense to mention this capability in the Ariadne's documentation as well.

Yes, I'll put this on my radar to add a doc about query fragments.

**Comment by rafalp** [comment]
I've opened a PR adding a piece on fragments to Ariadne's docs. I'll give it another look after the weekend and then merge it.
