### ISSUE TITLE
Using enums as argument default values is broken on InterfaceType

### ISSUE THREAD

**Issue by dkbarn** [mirumee/ariadne#995]
Similar to #547 but this bug is specific to type "interface". It seems that if you try to define a schema in which an interface type contains an enum argument with a default value, an error will be thrown when trying to execute an introspection query. This is with:

**ariadne 0.16.1**
**graphql-core 3.2.3**

Example:
```
import enum
import ariadne

type_defs = """
    type Query {
        users: [User!]!
    }

    enum Role {
        ADMIN
        USER
    }

    interface User {
        name(role: Role! = USER): String!
    }
"""

QueryGraphQLType = ariadne.QueryType()

class Role(enum.Enum):
    ADMIN = "ADMIN"
    USER = "USER"

RoleGraphQLType = ariadne.EnumType("Role", Role)

UserGraphQLType = ariadne.InterfaceType("User")

schema = ariadne.make_executable_schema(
    type_defs,
    QueryGraphQLType,
    RoleGraphQLType,
    UserGraphQLType,
)

query = "{__schema{types{name,fields{name,args{name,defaultValue}}}}}"

result = ariadne.graphql_sync(schema, {"query": query}, debug=True)
import pprint
pprint.pprint(result)
```

Error:
```
Enum 'Role' cannot represent value: 'USER'

GraphQL request:1:44
1 | {__schema{types{name,fields{name,args{name,defaultValue}}}}}
  |                                            ^
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
  File "/venv/lib/python3.8/site-packages/graphql/type/introspection.py", line 485, in default_value
    value_ast = ast_from_value(item[1].default_value, item[1].type)
  File "/venv/lib/python3.8/site-packages/graphql/utilities/ast_from_value.py", line 63, in ast_from_value
    ast_value = ast_from_value(value, type_.of_type)
  File "/venv/lib/python3.8/site-packages/graphql/utilities/ast_from_value.py", line 108, in ast_from_value
    serialized = type_.serialize(value)  # type: ignore
  File "/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 1233, in serialize
    raise GraphQLError(
graphql.error.graphql_error.GraphQLError: Enum 'Role' cannot represent value: 'USER'
```

**Comment by rafalp** [comment]
From traceback it seems that this is an issue with [graphql-core](https://github.com/graphql-python/graphql-core) and not with Ariadne?

**Comment by dkbarn** [comment]
It's not clear to me which library is at fault, the exception being raised is in the exact same function of graphql-core as #547 and that particular issue was patched in ariadne, so I thought maybe that patch was missing this edge case.

**Comment by rafalp** [comment]
Right, it may be as simple fix as adding Interface path to our [enums fixer](https://github.com/mirumee/ariadne/blob/master/ariadne/enums.py#L146).

**Comment by rafalp** [comment]
That seems to have fixed it. It's not likely for proper bugfix release because I have like 4 workhours left in this year before going for vacation, but I'll release 0.17.1 beta with the fix to let you test if my changes will solve this for you, @dkbarn

**Comment by dkbarn** [comment]
That would be great if you could put out a beta, thanks!

**Comment by rafalp** [comment]
Released fix in Ariadne 0.17.1b1. I'll keep this task open and on me so I remember to do a proper release in January when I'm back in the office.

**Comment by dkbarn** [comment]
Confirmed that 0.17.1b1 resolves the issue. Many thanks! Will look forward to a proper release in the new year.

**Comment by rafalp** [comment]
0.17.1 released, moving on to making announcements.
