### ISSUE TITLE
`explorer` module not distributed in 0.17.0

### ISSUE THREAD

**Issue by pylipp** [mirumee/ariadne#999]
I tried to experiment with different API explorers but it seems the explorer module is not distributed in the wheels (both when installing with `pip install -U ariadne` and when downloading the wheel from https://pypi.org/project/ariadne/#files and installing it in a fresh venv). 
`python -m pip list | grep ariadne` shows 0.17.0 but `ls ~/.virtualenvs/ariadne/lib/python3.7/site-packages/ariadne` does not show an `explorer` module.

Also I cannot see the `explorer` option in the `graphql` methods though the release notes say differently. Is it possible that an old package was distributed as 0.17?

**Comment by rafalp** [comment]
Hey, where do you see that there's explorer option in Ariadne 0.17? [Changelog](https://github.com/mirumee/ariadne/releases/tag/0.17.0) doesn't mention that.

We've originally released those as 0.17 dev, but devv releases have zero guarantees to be representative of final release (or even beta), those are just snapshots of whatever branch those were made of at the time of release. I guess I'll delete those releases after they served their purpose to don't confuse the people... or better yet, always have master in shippable state ;)

Sorry for the commotion.

**Comment by pylipp** [comment]
Alright, confusion was on my end then (dependabot notified me about a new release for ariadne and also listed dev-releases, so I was wondering why the explorer-module did not end up in 0.17). Thanks for clarification.
Is it planned to have different explorer options in a main release?

**Comment by rafalp** [comment]
Current plan is to release 0.17.1 with bugfix early in January (when I'm back in the office), then one more feature for 0.18 (case conversion as setting on `make_executable_schema` and not fallback resolver/resolver decorator), then write docs for 0.18 and release it. So `explorers` will also release as part of 0.18.
